import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    home: "Home",
    nearby_equipment: "Nearby Equipment",
    list_equipment: "List Your Equipment",
    nearby_storage: "Nearby Storage & Cold Storage",
    list_storage: "List Your Storage Facility",
    shared_transport: "Shared Transport",
    weather: "Weather",
    community: "Community",
    market: "Market",
    expert_qa: "Expert Q&A",
    notifications: "Notifications",
    profile: "Profile",
    good_morning: "Good Morning",
    your_farm_dashboard: "Your Farm Dashboard",
    weather_overview: "Weather Overview",
    current_conditions: "Current Conditions",
    actionable_advisories: "Actionable Advisories",
    seven_day_forecast: "7-Day Forecast",
    login_to_farmogram: "Login to Farmogram",
    mobile_number: "Mobile Number",
    password: "Password",
    register_your_farm: "Register Your Farm",
    farmer_onboarding: "Farmer Onboarding",
    full_name: "Farmer Full Name",
    next: "Next",
    back: "Back",
    create_password: "Create Password",
    confirm_password: "Confirm Password",
    select_language: "Select Your Language",
    state: "State",
    district: "District",
    land_acres: "Cultivable Land (Acres)",
    soil_type: "Dominant Soil Type",
    primary_crops: "Primary Crops Cultivated",
    create_profile: "Create Farmer Profile & Enter",
    select_state: "Select your State",
    select_district: "Select your District",
    select_soil: "Select Soil Type",
    search: "Search...",
    recommended_for_you: "Recommended For You",
    step_language: "Select Language",
    step_basic_info: "Basic Information",
    step_security: "Account Security",
    step_state: "Farm Location (State)",
    step_district: "District & Land Details",
    placeholder_name: "e.g., Ramasamy K.",
    placeholder_phone: "+91 94432 10987",
    mobile_verified: "Mobile number verified successfully. Create a password for your account.",
    already_registered: "Already registered?",
    login_here: "Login Here",
    market_prices: "Live Market Prices",
    disease_detection: "Disease Detection",
    irrigation: "Irrigation",
    settings: "Settings",
    admin_view: "Admin View",
    farmer_view: "Farmer View",
    profit: "Profit",
    schemes: "Schemes",
    qa: "Q&A",
    smart_agri_decision: "Smart Agri Decision & Community",
    main_navigation: "MAIN NAVIGATION",
    management: "MANAGEMENT",
    settings_subtitle: "Manage your preferences and app experience",
    language_region: "Language & Region",
    app_language: "App Language",
    select_pref_lang: "Select your preferred language for the application",
    push_notifications: "Push Notifications",
    receive_alerts: "Receive alerts for weather updates and advisories",
    accessibility: "Accessibility",
    high_contrast: "High Contrast Mode",
    increase_contrast: "Increase contrast for better readability",
    about_farmogram: "About Farmogram",
    version_info: "Version 1.0.0 (SIH 2026 Prototype)"
,

    location: "Location:",
    temperature: "Temperature:",
    primary_soil: "Primary Soil:",
    active_crops_in_season: "Active Crops in Season",
    agricultural_advisory: "Agricultural Advisory:",
    high_priority: "High Priority",
    view_weather_advisory: "View Weather Advisory",
    decision_support_tools: "Decision Support Tools",
    pre_sowing_intelligence: "Pre-sowing to post-harvest intelligence",
    crop_advisor_desc: "AI Multi-factor agronomic advice",
    high_precision: "High Precision",
    weather_advisory: "Weather Advisory",
    weather_advisory_desc: "7-day microclimate forecast",
    rain_alert: "Rain Alert",
    disease_desc: "Scan leaf lesions for remedies",
    instant_ai: "Instant AI",
    irrigation_desc: "Weather & stage-based schedule",
    water_saving: "Water Saving",
    market_prices_desc: "Live Mandi rates & trends",
    tomato_up: "Tomato ↑ 8%",
    profit_calculator: "Profit Calculator",
    profit_desc: "Calculate costs, yield & ROI",
    financials: "Financials",
    open_tool: "Open Tool",
    community_hub_title: "🌾 Farmogram Community & Knowledge Hub",
    community_hub_subtitle: "Real experiences, verified advice & agronomic practices from Indian farmers",
    share_experience: "Share Your Experience",
    // Tools & Actions
    crop_advisor: "Crop Advisor",
    transport_pooling: "Shared Transport Pooling",
    transport_pooling_desc: "Share vehicle with nearby farmers heading to market & split costs.",
    save_money: "Save ₹800+",
    connect_agronomist: "Connect with Local Agronomist",
    ready_scan: "Ready for Diagnostic Scan",
    ready_scan_desc: "Click 'Analyze Crop Disease' to start image classification and view complete symptoms, organic remedies, and chemical controls.",
    upload_leaf_photo: "Upload Foliar / Leaf Photograph",
    upload_leaf_sub: "Take a close-up photo of infected leaves showing lesions or discoloration.",
    drag_drop_leaf: "Click to upload or drag & drop leaf image",
    png_jpg_max: "PNG, JPG, JPEG up to 10MB",
    replace_image: "Replace Image",
    scanning_morphology: "Scanning leaf morphology & lesion patterns...",
    analyzing_engine: "AI Vision Engine Analyzing...",
    analyze_crop_disease: "Analyze Crop Disease",
    detected_crop: "Detected Crop",
    observed_symptoms: "Observed Symptoms",
    ai_analysis_report: "Detailed AI Analysis Report",
    preventive_measures: "Cultural & Preventive Measures",
    treatment_protocol: "Recommended Treatment Protocol",
    step_label: "Step",
    confidence: "Confidence",

    // Smart SOS & Wildlife Incident Reporting
    sos_banner_badge: "EMERGENCY WILDLIFE & FARM THREAT DISPATCH",
    sos_banner_title: "24/7 Smart SOS & Incident Reporting",
    sos_banner_desc: "Elephant intrusion, wild boar herd, leopard / tiger sighting, snake bites, or crop destruction? Instantly alert your local Forest Range Officer & Rapid Response Team (RRT) with verified GPS routing and original voice note.",
    sos_launch_report: "LAUNCH SOS REPORT",
    sos_modal_title: "Smart SOS & Emergency Dispatch",
    sos_modal_sub: "Direct Wildlife Conflict & Government Authority Routing",
    sos_step1_title: "What type of SOS do you need?",
    sos_step1_desc: "Select the wild animal or emergency category to alert the nearest forest range or rescue authority.",
    sos_elephant_name: "Elephant",
    sos_elephant_tag: "Elephant near farm / crop damage / danger",
    sos_wild_boar_name: "Wild Boar / Pig",
    sos_wild_boar_tag: "Wild boar near farm / crop damage",
    sos_monkey_name: "Monkey",
    sos_monkey_tag: "Monkey troop intrusion / crop damage",
    sos_leopard_name: "Leopard / Tiger",
    sos_leopard_tag: "Dangerous big cat / immediate threat",
    sos_bear_name: "Bear",
    sos_bear_tag: "Bear sighting / farm intrusion",
    sos_snake_name: "Snake",
    sos_snake_tag: "Snake emergency / venom risk",
    sos_other_wildlife_name: "Other Wildlife",
    sos_other_wildlife_tag: "Deer, gaur, or other wild animal",
    sos_other_sos_name: "Other SOS",
    sos_other_sos_tag: "Fire, medical, theft, farm disaster",
    sos_back_animal: "Back to Animal Selection",
    sos_select_other_title: "Select Other Emergency Category",
    sos_select_other_desc: "We will dispatch this report to the verified local emergency department (Fire, Police, or Veterinary).",
    sos_other_fire: "Fire Emergency",
    sos_other_fire_desc: "Crop fire, barn or shed blaze",
    sos_other_flood: "Flood / Water Surge",
    sos_other_flood_desc: "Canal breach or field inundation",
    sos_other_theft: "Theft / Security",
    sos_other_theft_desc: "Trespassing or produce theft",
    sos_other_livestock: "Livestock Emergency",
    sos_other_livestock_desc: "Injured cattle, rabies threat",
    sos_other_human: "Human Safety Threat",
    sos_other_human_desc: "Worker injured or stranded",
    sos_other_storm: "Storm / Tree Fall",
    sos_other_storm_desc: "Electrical wire drop or cyclone",
    sos_incident_detected: "Incident Detected",
    sos_step_verifying: "Step 1 of 3: Verifying GPS & Jurisdiction",
    sos_live_gps: "📍 Your Live GPS Location",
    sos_jurisdiction: "🏛️ Forest Jurisdiction: Sathyamangalam / Hasanur Buffer Division",
    sos_resp_authority: "RESPONSIBLE GOVERNMENT AUTHORITY",
    sos_authority_desc: "Tamil Nadu Forest Department • Toll-Free Wildlife Helpline: 1800-425-4545 / 1926",
    sos_change_type: "Change Type",
    sos_confirm_location: "Confirm Location & Next ➔",
    sos_voice_choice_title: "Would you like to tell the officer what happened?",
    sos_voice_choice_desc: "You can speak naturally in your own language. Your actual original voice recording will reach the officer directly.",
    sos_speak_title: "🎤 Speak",
    sos_speak_desc: "Record a voice message describing what you see. Officer will play your actual recording.",
    sos_no_voice_title: "➡️ Continue Without Voice",
    sos_no_voice_desc: "Immediately send your GPS location and structured SOS details without recording audio.",
    sos_tell_happened: "🎤 Tell Us What Happened",
    sos_tell_happened_desc: "Explain the animal position, crop damage, or danger. Speak naturally in your own language.",
    sos_tap_record: "Tap mic to start recording",
    sos_recording_stop: "● Recording... Tap square to stop",
    sos_rec_captured: "✓ Voice Recording Captured",
    sos_listen_voice: "Listen to Voice",
    sos_pause_playback: "Pause Playback",
    sos_rerecord: "Re-record",
    sos_voice_guarantee: "💡 This exact original voice note will be delivered to the Forest Duty Officer.",
    sos_send_with_voice: "Send SOS with Voice Note ➔",
    sos_assessment_title: "Quick Incident Assessment",
    sos_assessment_desc: "Select quick answers to help authorities prioritize the emergency response:",
    sos_danger_immediate: "⚠️ Human Safety in Immediate Danger",
    sos_danger_immediate_sub: "People or children are nearby and threatened",
    sos_animal_present: "Animal is currently present on the farm",
    sos_animal_present_sub: "Visible right now in fields or boundary",
    sos_damage_ongoing: "Crop or irrigation infrastructure damaged",
    sos_damage_ongoing_sub: "Sugarcane, banana, tomatoes, or drip pipes damaged",
    sos_send_now: "Send SOS Now ➔",
    sos_sent_success: "SOS Sent Successfully!",
    sos_incident_ref: "Emergency Incident Reference:",
    sos_type_col: "INCIDENT TYPE",
    sos_gps_col: "GPS LOCATION",
    sos_voice_col: "VOICE NOTE",
    sos_status_col: "STATUS",
    sos_transmitted: "✓ Transmitted",
    sos_delivered: "✓ Delivered",
    sos_no_voice: "No Voice Sent",
    sos_realtime_status: "🚨 Real-Time Dispatch Status",
    sos_safety_instructions: "🛡️ Immediate Safety Instructions:",
    sos_call_authority_btn: "Call Authority",
    sos_done_close: "Done & Close",
    sos_safety_elephant: "Stay at a safe distance (at least 150m) from elephants. Do not shine flashlights directly into their eyes or make loud sudden noises. Keep farm perimeter lights ON and retreat to a reinforced building.",
    sos_safety_boar: "Do not corner or chase wild boars; females with piglets can charge aggressively. Avoid walking through dense sugarcane or tall crops alone until forest patrol arrives.",
    sos_safety_leopard: "Immediate Threat: Move children and livestock indoors immediately. Lock cattle sheds. Do not crouch or bend down in open fields. Keep lights on and stay inside until forest guards arrive.",
    sos_safety_bear: "Do not run if you spot a sloth bear. Slowly back away without turning your back. Avoid sudden hand movements and make steady, calm human voices so it knows your position and moves away.",
    sos_safety_snake: "Do not attempt to catch or kill the snake. Keep pets and family members away. If someone is bitten, keep the bitten limb immobile below heart level and proceed immediately to the nearest Taluk Hospital for Anti-Snake Venom (ASV).",
    sos_safety_fire: "Move away from the smoke direction. Turn off farm electricity mains and fuel engines. If safe, create a cleared buffer break between dry crops and farm sheds.",
    sos_safety_default: "Stay at a safe distance from the threat. Do not approach or provoke wild animals. Move to a secure location and await guidance from verified government authorities.",

    // Crops & Soils
    "Paddy": "Paddy",
    "Tomato": "Tomato",
    "Groundnut": "Groundnut",
    "Sugarcane": "Sugarcane",
    "Cotton": "Cotton",
    "Banana": "Banana",
    "Maize": "Maize",
    "Turmeric": "Turmeric",
    "Red Loam": "Red Loam",
    "Clayey Alluvial": "Clayey Alluvial",
    "Black Cotton Soil (Regur)": "Black Cotton Soil (Regur)",
    "Sandy Loam": "Sandy Loam",
    "Laterite Soil": "Laterite Soil"
  },
  hi: {
    home: "होम",
    nearby_equipment: "निकटतम कृषि उपकरण",
    list_equipment: "उपकरण किराए पर दें",
    nearby_storage: "निकटतम गोदाम और कोल्ड स्टोरेज",
    list_storage: "गोदाम या कोल्ड स्टोरेज पंजीकृत करें",
    shared_transport: "साझा परिवहन",
    weather: "मौसम",
    community: "समुदाय",
    market: "बाज़ार",
    expert_qa: "विशेषज्ञ प्रश्नोत्तर",
    notifications: "सूचनाएं",
    profile: "प्रोफ़ाइल",
    good_morning: "सुप्रभात",
    your_farm_dashboard: "आपका कृषि डैशबोर्ड",
    weather_overview: "मौसम अवलोकन",
    current_conditions: "वर्तमान स्थिति",
    actionable_advisories: "कार्रवाई योग्य सलाह",
    seven_day_forecast: "7-दिवसीय पूर्वानुमान",
    login_to_farmogram: "फार्मोग्राम में लॉगिन करें",
    mobile_number: "मोबाइल नंबर",
    password: "पासवर्ड",
    register_your_farm: "अपना खेत पंजीकृत करें",
    farmer_onboarding: "किसान पंजीकरण",
    full_name: "किसान का पूरा नाम",
    next: "अगला",
    back: "पीछे",
    create_password: "पासवर्ड बनाएं",
    confirm_password: "पासवर्ड की पुष्टि करें",
    select_language: "अपनी भाषा चुनें",
    state: "राज्य",
    district: "ज़िला",
    land_acres: "कृषि योग्य भूमि (एकड़)",
    soil_type: "प्रमुख मिट्टी का प्रकार",
    primary_crops: "मुख्य फसलें",
    create_profile: "किसान प्रोफाइल बनाएं और प्रवेश करें",
    select_state: "अपना राज्य चुनें",
    select_district: "अपना ज़िला चुनें",
    select_soil: "मिट्टी का प्रकार चुनें",
    search: "खोजें...",
    recommended_for_you: "आपके लिए अनुशंसित",
    market_prices: "लाइव बाजार मूल्य",
    disease_detection: "रोग पहचान",
    irrigation: "सिंचाई",
    settings: "सेटिंग्स",
    admin_view: "एडमिन व्यू",
    farmer_view: "किसान व्यू",
    profit: "मुनाफा",
    schemes: "योजनाएं",
    qa: "प्रश्नोत्तर",
    smart_agri_decision: "स्मार्ट कृषि निर्णय और समुदाय",
    main_navigation: "मुख्य नेविगेशन",
    management: "प्रबंधन",
    settings_subtitle: "अपनी प्राथमिकताएं प्रबंधित करें",
    language_region: "भाषा और क्षेत्र",
    app_language: "ऐप की भाषा",
    select_pref_lang: "अपनी पसंदीदा भाषा चुनें",
    push_notifications: "पुश सूचनाएँ",
    receive_alerts: "मौसम और सलाह के लिए अलर्ट प्राप्त करें",
    accessibility: "अभिगम्यता",
    high_contrast: "उच्च कंट्रास्ट मोड",
    increase_contrast: "बेहतर पठनीयता के लिए कंट्रास्ट बढ़ाएं",
    about_farmogram: "फार्मोग्राम के बारे में",
    version_info: "संस्करण 1.0.0 (SIH 2026 प्रोटोटाइप)"
,

    location: "स्थान:",
    temperature: "तापमान:",
    primary_soil: "प्राथमिक मिट्टी:",
    active_crops_in_season: "सीज़न में सक्रिय फसलें",
    agricultural_advisory: "कृषि सलाहकार:",
    high_priority: "उच्च प्राथमिकता",
    view_weather_advisory: "मौसम सलाहकार देखें",
    decision_support_tools: "निर्णय समर्थन उपकरण",
    pre_sowing_intelligence: "बुवाई से कटाई तक की जानकारी",
    crop_advisor_desc: "AI बहु-कारक कृषि सलाह",
    high_precision: "उच्च सटीकता",
    weather_advisory: "मौसम सलाहकार",
    weather_advisory_desc: "7-दिवसीय सूक्ष्म जलवायु पूर्वानुमान",
    rain_alert: "बारिश का अलर्ट",
    disease_desc: "उपाय के लिए पत्तियों के घाव स्कैन करें",
    instant_ai: "त्वरित AI",
    irrigation_desc: "मौसम और चरण-आधारित अनुसूची",
    water_saving: "जल बचत",
    market_prices_desc: "लाइव मंडी दरें और रुझान",
    tomato_up: "टमाटर ↑ 8%",
    profit_calculator: "मुनाफा कैलकुलेटर",
    profit_desc: "लागत, उपज और ROI की गणना करें",
    financials: "वित्तीय",
    open_tool: "उपकरण खोलें",
    community_hub_title: "🌾 फार्मोग्राम समुदाय और ज्ञान केंद्र",
    community_hub_subtitle: "भारतीय किसानों के वास्तविक अनुभव, सत्यापित सलाह और कृषि पद्धतियां",
    share_experience: "अपना अनुभव साझा करें",
    // Tools & Actions
    crop_advisor: "फसल सलाहकार",
    transport_pooling: "साझा परिवहन पूलिंग",
    transport_pooling_desc: "मंडी जाने वाले नजदीकी किसानों के साथ वाहन साझा करें और खर्च बचाएं।",
    save_money: "₹800+ की बचत",
    connect_agronomist: "स्थानीय कृषि अधिकारी से संपर्क करें",
    ready_scan: "रोग जांच के लिए तैयार",
    ready_scan_desc: "'फसल रोग का विश्लेषण करें' पर क्लिक करें और पूर्ण लक्षण, जैविक उपचार व रासायनिक नियंत्रण देखें।",
    upload_leaf_photo: "प्रभावित पत्ती की तस्वीर अपलोड करें",
    upload_leaf_sub: "धब्बे या रंग परिवर्तन वाली पत्तियों की नजदीकी फोटो लें।",
    drag_drop_leaf: "पत्ती की तस्वीर अपलोड करने के लिए क्लिक करें या खींचकर छोड़ें",
    png_jpg_max: "PNG, JPG, JPEG अधिकतम 10MB",
    replace_image: "तस्वीर बदलें",
    scanning_morphology: "पत्ती की संरचना और धब्बों की जांच हो रही है...",
    analyzing_engine: "एआई इंजन विश्लेषण कर रहा है...",
    analyze_crop_disease: "फसल रोग का विश्लेषण करें",
    detected_crop: "पहचानी गई फसल",
    observed_symptoms: "देखे गए रोग लक्षण",
    ai_analysis_report: "विस्तृत एआई विश्लेषण रिपोर्ट",
    preventive_measures: "निवारक एवं प्रबंधन उपाय",
    treatment_protocol: "अनुशंसित उपचार प्रोटोकॉल",
    step_label: "चरण",
    confidence: "सटीकता",

    // Smart SOS & Wildlife Incident Reporting
    sos_banner_badge: "आपातकालीन वन्यजीव व कृषि संकट प्रेषण",
    sos_banner_title: "24/7 स्मार्ट एसओएस व घटना रिपोर्टिंग",
    sos_banner_desc: "हाथी का प्रवेश, जंगली सूअर, तेंदुआ/बाघ दिखना, सांप का काटना या फसल बर्बादी? जीपीएस लोकेशन और आवाज संदेश के साथ वन विभाग व त्वरित प्रतिक्रिया दल को तुरंत सतर्क करें।",
    sos_launch_report: "आपातकालीन रिपोर्ट भेजें (SOS)",
    sos_modal_title: "स्मार्ट एसओएस और आपातकालीन प्रेषण",
    sos_modal_sub: "वन्यजीव संघर्ष व सरकारी प्राधिकरण को त्वरित जीपीएस प्रेषण",
    sos_step1_title: "आपको किस प्रकार की आपातकालीन सहायता चाहिए?",
    sos_step1_desc: "निकटतम वन परिक्षेत्र या बचाव दल को सतर्क करने के लिए वन्यजीव या आपात श्रेणी चुनें।",
    sos_elephant_name: "हाथी",
    sos_elephant_tag: "खेत के पास हाथी / फसल नुकसान / खतरा",
    sos_wild_boar_name: "जंगली सूअर",
    sos_wild_boar_tag: "खेत के पास जंगली सूअर / फसल बर्बादी",
    sos_monkey_name: "बंदरों का झुंड",
    sos_monkey_tag: "बंदरों का आक्रमण / बागवानी नुकसान",
    sos_leopard_name: "तेंदुआ / बाघ",
    sos_leopard_tag: "खतरनाक हिंसक जानवर / तत्काल जान का खतरा",
    sos_bear_name: "भालू",
    sos_bear_tag: "भालू दिखना / खेत में घुसपैठ",
    sos_snake_name: "सांप",
    sos_snake_tag: "जहरीला सांप / काटने का खतरा",
    sos_other_wildlife_name: "अन्य वन्यजीव",
    sos_other_wildlife_tag: "हिरण, नीलगाय, गौर या अन्य जंगली जानवर",
    sos_other_sos_name: "अन्य आपातकाल",
    sos_other_sos_tag: "आग, चिकित्सा, चोरी, कृषि आपदा",
    sos_back_animal: "वन्यजीव चयन पर वापस जाएं",
    sos_select_other_title: "अन्य आपातकालीन श्रेणी चुनें",
    sos_select_other_desc: "यह रिपोर्ट स्थानीय अग्निशमन, पुलिस या पशु चिकित्सा विभाग को भेजी जाएगी।",
    sos_other_fire: "आग का आपातकाल",
    sos_other_fire_desc: "फसल में आग, खलिहान या बाड़े में आग",
    sos_other_flood: "बाढ़ / जलभराव",
    sos_other_flood_desc: "नहर टूटना या खेत में पानी भरना",
    sos_other_theft: "चोरी / सुरक्षा",
    sos_other_theft_desc: "अनाधिकृत प्रवेश या उपज की चोरी",
    sos_other_livestock: "पशु आपातकाल",
    sos_other_livestock_desc: "घायल मवेशी, रेबीज का खतरा",
    sos_other_human: "मानव सुरक्षा खतरा",
    sos_other_human_desc: "श्रमिक घायल या फंसा हुआ",
    sos_other_storm: "तूफान / पेड़ गिरना",
    sos_other_storm_desc: "बिजली का तार गिरना या चक्रवाती नुकसान",
    sos_incident_detected: "घटना दर्ज की गई",
    sos_step_verifying: "चरण 1/3: जीपीएस व क्षेत्राधिकार सत्यापन",
    sos_live_gps: "📍 आपकी लाइव जीपीएस लोकेशन",
    sos_jurisdiction: "🏛️ वन क्षेत्राधिकार: सत्यमंगलम / इरोड प्रभाग",
    sos_resp_authority: "जिम्मेदार सरकारी प्राधिकरण",
    sos_authority_desc: "तमिलनाडु वन विभाग • टोल-फ्री वन्यजीव हेल्पलाइन: 1800-425-4545 / 1926",
    sos_change_type: "प्रकार बदलें",
    sos_confirm_location: "स्थान की पुष्टि करें और आगे बढ़ें ➔",
    sos_voice_choice_title: "क्या आप वन अधिकारी को बोलकर बताना चाहते हैं?",
    sos_voice_choice_desc: "आप अपनी भाषा में स्वाभाविक रूप से बोल सकते हैं। आपकी मूल आवाज सीधे अधिकारी तक पहुंचेगी।",
    sos_speak_title: "🎤 बोलकर बताएं",
    sos_speak_desc: "स्थिति बताते हुए आवाज रिकॉर्ड करें। अधिकारी आपकी वास्तविक आवाज सुनेंगे।",
    sos_no_voice_title: "➡️ बिना आवाज आगे बढ़ें",
    sos_no_voice_desc: "बिना आवाज रिकॉर्ड किए तुरंत अपनी जीपीएस लोकेशन और विवरण भेजें।",
    sos_tell_happened: "🎤 बताएं क्या हुआ है",
    sos_tell_happened_desc: "जानवर की स्थिति, फसल क्षति या खतरे को समझाएं। अपनी भाषा में स्पष्ट बोलें।",
    sos_tap_record: "रिकॉर्डिंग शुरू करने के लिए माइक दबाएं",
    sos_recording_stop: "● रिकॉर्डिंग जारी है... रोकने के लिए वर्ग दबाएं",
    sos_rec_captured: "✓ आवाज रिकॉर्ड हो गई",
    sos_listen_voice: "आवाज सुनें",
    sos_pause_playback: "रोकें",
    sos_rerecord: "फिर से रिकॉर्ड करें",
    sos_voice_guarantee: "💡 यह मूल आवाज सीधे वन ड्यूटी अधिकारी को भेजी जाएगी।",
    sos_send_with_voice: "आवाज के साथ एसओएस भेजें ➔",
    sos_assessment_title: "त्वरित स्थिति आकलन",
    sos_assessment_desc: "अधिकारियों को प्राथमिकता तय करने में मदद के लिए उत्तर चुनें:",
    sos_danger_immediate: "⚠️ मानव सुरक्षा को तत्काल खतरा है",
    sos_danger_immediate_sub: "लोग या बच्चे आसपास हैं और खतरे में हैं",
    sos_animal_present: "जानवर वर्तमान में खेत में मौजूद है",
    sos_animal_present_sub: "खेत या मेड़ पर अभी दिखाई दे रहा है",
    sos_damage_ongoing: "फसल या बुनियादी ढांचे को नुकसान पहुंचा है",
    sos_damage_ongoing_sub: "गन्ना, केला, टमाटर या ड्रिप पाइप को नुकसान",
    sos_send_now: "अभी एसओएस भेजें ➔",
    sos_sent_success: "एसओएस सफलतापूर्वक भेजा गया!",
    sos_incident_ref: "आपातकालीन संदर्भ संख्या:",
    sos_type_col: "घटना का प्रकार",
    sos_gps_col: "जीपीएस स्थान",
    sos_voice_col: "आवाज संदेश",
    sos_status_col: "स्थिति",
    sos_transmitted: "✓ प्रेषित",
    sos_delivered: "✓ प्राप्त",
    sos_no_voice: "कोई आवाज नहीं",
    sos_realtime_status: "🚨 लाइव प्रेषण स्थिति",
    sos_safety_instructions: "🛡️ तत्काल सुरक्षा निर्देश:",
    sos_call_authority_btn: "अधिकारी को कॉल करें",
    sos_done_close: "पूर्ण व बंद करें",
    sos_safety_elephant: "हाथियों से कम से कम 150 मीटर सुरक्षित दूरी बनाए रखें। उनकी आंखों पर सीधे टॉर्च न मारें। खेत की लाइटें चालू रखें और पक्के भवन में शरण लें।",
    sos_safety_boar: "जंगली सूअरों को घेरने या भगाने की कोशिश न करें; बच्चों वाली मादा सूअर हमला कर सकती है। घने गन्ने या मक्के के खेतों में अकेले न जाएं।",
    sos_safety_leopard: "तत्काल खतरा: बच्चों और पशुओं को तुरंत सुरक्षित स्थान पर ले जाएं। मवेशी बाड़े को बंद करें। खुले खेतों में झुककर न बैठें और वन रक्षकों की प्रतीक्षा करें।",
    sos_safety_bear: "भालू दिखने पर भागें नहीं। पीठ दिखाए बिना धीरे-धीरे पीछे हटें। अचानक हाथ न हिलाएं और सामान्य आवाज में बोलें ताकि वह रास्ता बदल ले।",
    sos_safety_snake: "सांप को पकड़ने या मारने की कोशिश न करें। काटे जाने पर काटे हुए हिस्से को हृदय के स्तर से नीचे रखें और सीधे अस्पताल जाएं।",
    sos_safety_fire: "धुएं की दिशा से दूर हटें। मुख्य बिजली स्विच बंद करें और सुरक्षित दूरी बनाए रखें।",
    sos_safety_default: "खतरे से सुरक्षित दूरी बनाए रखें। जंगली जानवरों को न उकसाएं और सरकारी सहायता की प्रतीक्षा करें।",

    // Crops & Soils
    "Paddy": "धान (Paddy)",
    "Tomato": "टमाटर",
    "Groundnut": "मूंगफली",
    "Sugarcane": "गन्ना",
    "Cotton": "कपास",
    "Banana": "केला",
    "Maize": "मक्का",
    "Turmeric": "हल्दी",
    "Red Loam": "लाल दोमट मिट्टी",
    "Clayey Alluvial": "चिकनी जलोढ़ मिट्टी",
    "Black Cotton Soil (Regur)": "काली कपास मिट्टी (रेगुर)",
    "Sandy Loam": "रेतीली दोमट मिट्टी",
    "Laterite Soil": "लेटराइट मिट्टी"
  },
  ta: {
    home: "முகப்பு",
    nearby_equipment: "அருகிலுள்ள உபகரணங்கள்",
    list_equipment: "உபகரணங்களை பட்டியலிடுக",
    nearby_storage: "அருகிலுள்ள சேமிப்பு & குளிர்பதன கிடங்கு",
    list_storage: "சேமிப்பு கிடங்கை பதிவு செய்க",
    shared_transport: "பகிர்வு போக்குவரத்து",
    weather: "வானிலை",
    community: "சமூகம்",
    market: "சந்தை",
    expert_qa: "நிபுணர் கேள்வி பதில்",
    notifications: "அறிவிப்புகள்",
    profile: "சுயவிவரம்",
    good_morning: "காலை வணக்கம்",
    your_farm_dashboard: "உங்கள் பண்ணை முகப்பு",
    weather_overview: "வானிலை கண்ணோட்டம்",
    current_conditions: "தற்போதைய நிலை",
    actionable_advisories: "செயல்படக்கூடிய ஆலோசனைகள்",
    seven_day_forecast: "7 நாள் கணிப்பு",
    login_to_farmogram: "உள்நுழைய",
    mobile_number: "மொபைல் எண்",
    password: "கடவுச்சொல்",
    register_your_farm: "பண்ணையை பதிவு செய்க",
    farmer_onboarding: "விவசாயி பதிவு",
    full_name: "விவசாயி முழு பெயர்",
    next: "அடுத்து",
    back: "பின்",
    create_password: "கடவுச்சொல் உருவாக்கு",
    confirm_password: "கடவுச்சொல்லை உறுதிப்படுத்து",
    select_language: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    state: "மாநிலம்",
    district: "மாவட்டம்",
    land_acres: "விவசாய நிலம் (ஏக்கர்)",
    soil_type: "மண் வகை",
    primary_crops: "முதன்மை பயிர்கள்",
    create_profile: "சுயவிவரத்தை உருவாக்கி உள்ளே நுழைக",
    select_state: "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
    select_district: "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்",
    select_soil: "மண் வகையைத் தேர்ந்தெடுக்கவும்",
    search: "தேடு...",
    recommended_for_you: "பரிந்துரைக்கப்படுபவை",
    step_language: "மொழியைத் தேர்ந்தெடுக்கவும்",
    step_basic_info: "அடிப்படை தகவல்",
    step_security: "கணக்கு பாதுகாப்பு",
    step_state: "பண்ணை இடம் (மாநிலம்)",
    step_district: "மாவட்டம் மற்றும் நில விவரங்கள்",
    placeholder_name: "உதா: ராமசாமி கி.",
    placeholder_phone: "+91 94432 10987",
    mobile_verified: "மொபைல் எண் சரிபார்க்கப்பட்டது. கடவுச்சொல்லை உருவாக்கவும்.",
    already_registered: "ஏற்கனவே பதிவு செய்துள்ளீர்களா?",
    login_here: "இங்கே உள்நுழையவும்",
    market_prices: "சந்தை விலைகள்",
    disease_detection: "நோய் கண்டறிதல்",
    irrigation: "நீர்ப்பாசனம்",
    settings: "அமைப்புகள்",
    admin_view: "நிர்வாகி பார்வை",
    farmer_view: "விவசாயி பார்வை",
    profit: "இலாபம்",
    schemes: "திட்டங்கள்",
    qa: "கேள்வி-பதில்",
    smart_agri_decision: "ஸ்மார்ட் வேளாண் முடிவு & சமூகம்",
    main_navigation: "முக்கிய வழிசெலுத்தல்",
    management: "மேலாண்மை",
    settings_subtitle: "உங்கள் விருப்பங்களை நிர்வகிக்கவும்",
    language_region: "மொழி & பகுதி",
    app_language: "பயன்பாட்டு மொழி",
    select_pref_lang: "விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    push_notifications: "அறிவிப்புகள்",
    receive_alerts: "வானிலை எச்சரிக்கைகளைப் பெறுக",
    accessibility: "அணுகல்",
    high_contrast: "உயர் மாறுபாடு பயன்முறை",
    increase_contrast: "வாசிப்புத்திறனை அதிகரிக்கவும்",
    about_farmogram: "பார்மோகிராம் பற்றி",
    version_info: "பதிப்பு 1.0.0 (SIH 2026 முன்மாதிரி)"
,

    location: "இடம்:",
    temperature: "வெப்பநிலை:",
    primary_soil: "முதன்மை மண்:",
    active_crops_in_season: "பருவத்தில் செயலில் உள்ள பயிர்கள்",
    agricultural_advisory: "வேளாண் ஆலோசனை:",
    high_priority: "அதிக முன்னுரிமை",
    view_weather_advisory: "வானிலை ஆலோசனையைக் காண்க",
    decision_support_tools: "முடிவு ஆதரவு கருவிகள்",
    pre_sowing_intelligence: "விதைப்பு முதல் அறுவடை வரை நுண்ணறிவு",
    crop_advisor_desc: "AI பல காரணி உழவியல் ஆலோசனை",
    high_precision: "உயர் துல்லியம்",
    weather_advisory: "வானிலை ஆலோசனை",
    weather_advisory_desc: "7-நாள் நுண்-கணிப்பு",
    rain_alert: "மழை எச்சரிக்கை",
    disease_desc: "தீர்வுகளுக்கு இலைப்புண்களை ஸ்கேன் செய்யுங்கள்",
    instant_ai: "உடனடி AI",
    irrigation_desc: "வானிலை & நிலை அடிப்படையிலான அட்டவணை",
    water_saving: "நீர் சேமிப்பு",
    market_prices_desc: "நேரலை மண்டி விலைகள்",
    tomato_up: "தக்காளி ↑ 8%",
    profit_calculator: "இலாப கணக்கீட்டான்",
    profit_desc: "செலவுகள், விளைச்சல் மற்றும் ROI",
    financials: "நிதியியல்",
    open_tool: "கருவியைத் திற",
    community_hub_title: "🌾 பார்மோகிராம் சமூகம் & அறிவு மையம்",
    community_hub_subtitle: "இந்திய விவசாயிகளின் உண்மையான அனுபவங்கள் & சரிபார்க்கப்பட்ட ஆலோசனைகள்",
    share_experience: "உங்கள் அனுபவத்தைப் பகிரவும்",
    
    // States
    "Andhra Pradesh": "ஆந்திரப் பிரதேசம்",
    "Arunachal Pradesh": "அருணாச்சல பிரதேசம்",
    "Assam": "அசாம்",
    "Bihar": "பீகார்",
    "Chandigarh (UT)": "சண்டிகர்",
    "Chhattisgarh": "சத்தீஸ்கர்",
    "Dadra and Nagar Haveli (UT)": "தாத்ரா மற்றும் நகர் ஹவேலி",
    "Daman and Diu (UT)": "டாமன் மற்றும் டையூ",
    "Delhi (NCT)": "டெல்லி",
    "Goa": "கோவா",
    "Gujarat": "குஜராத்",
    "Haryana": "ஹரியானா",
    "Himachal Pradesh": "இமாச்சல பிரதேசம்",
    "Jammu and Kashmir": "ஜம்மு காஷ்மீர்",
    "Jharkhand": "ஜார்க்கண்ட்",
    "Karnataka": "கர்நாடகா",
    "Kerala": "கேரளா",
    "Lakshadweep (UT)": "லட்சத்தீவு",
    "Madhya Pradesh": "மத்தியப் பிரதேசம்",
    "Maharashtra": "மகாராஷ்டிரா",
    "Manipur": "மணிப்பூர்",
    "Meghalaya": "மேகாலயா",
    "Mizoram": "மிசோரம்",
    "Nagaland": "நாகாலாந்து",
    "Odisha": "ஒடிசா",
    "Puducherry (UT)": "புதுச்சேரி",
    "Punjab": "பஞ்சாப்",
    "Rajasthan": "ராஜஸ்தான்",
    "Sikkim": "சிக்கிம்",
    "Tamil Nadu": "தமிழ்நாடு",
    "Telangana": "தெலுங்கானா",
    "Tripura": "திரிபுரா",
    "Uttar Pradesh": "உத்தரப் பிரதேசம்",
    "Uttarakhand": "உத்தரகாண்ட்",
    "West Bengal": "மேற்கு வங்காளம்",

    // Districts (Subset for testing)
    "Coimbatore": "கோயம்புத்தூர்",
    "Erode": "ஈரோடு",
    "Salem": "சேலம்",
    "Tiruppur": "திருப்பூர்",
    "Namakkal": "நாமக்கல்",

    // Soil Types
    "Red Loam": "செம்மண்",
    "Clayey Alluvial": "வண்டல் மண்",
    "Black Cotton Soil (Regur)": "கரிசல் மண்",
    "Sandy Loam": "மணற்பாங்கான மண்",
    "Laterite Soil": "செம்புரை மண்",

    // Crops
    "Paddy": "நெல்",
    "Tomato": "தக்காளி",
    "Groundnut": "நிலக்கடலை",
    "Sugarcane": "கரும்பு",
    "Cotton": "பருத்தி",
    "Banana": "வாழை",
    "Maize": "மக்காச்சோளம்",
    "Turmeric": "மஞ்சள்",
    // Tools & Actions
    crop_advisor: "பயிர் ஆலோசகர்",
    transport_pooling: "பகிர்வு சரக்கு போக்குவரத்து",
    transport_pooling_desc: "சந்தைக்குச் செல்லும் அருகில் உள்ள விவசாயிகளுடன் வாகனத்தைப் பகிர்ந்து செலவைக் குறைக்கவும்.",
    save_money: "₹800+ சேமிப்பு",
    connect_agronomist: "உள்ளூர் வேளாண் அதிகாரியை தொடர்பு கொள்ளவும்",
    ready_scan: "நோய் பரிசோதனைக்கு தயார்",
    ready_scan_desc: "'பயிர் நோயை பகுப்பாய்வு செய்க' பொத்தானை அழுத்தி முழுமையான அறிகுறிகள், இயற்கை மற்றும் ரசாயன சிகிச்சை முறைகளைக் காணுங்கள்.",
    upload_leaf_photo: "பாதிக்கப்பட்ட இலை புகைப்படத்தை பதிவேற்றவும்",
    upload_leaf_sub: "புள்ளிகள் அல்லது நிறமாற்றம் உள்ள இலையின் நெருக்கமான புகைப்படத்தை எடுக்கவும்.",
    drag_drop_leaf: "இலை புகைப்படத்தை பதிவேற்ற கிளிக் செய்யவும் அல்லது இழுத்து விடவும்",
    png_jpg_max: "PNG, JPG, JPEG அதிகபட்சம் 10MB",
    replace_image: "படத்தை மாற்றுக",
    scanning_morphology: "இலையின் அமைப்பை ஸ்கேன் செய்கிறது...",
    analyzing_engine: "AI துல்லிய பரிசோதனை செய்கிறது...",
    analyze_crop_disease: "பயிர் நோயை பகுப்பாய்வு செய்க",
    detected_crop: "கண்டறியப்பட்ட பயிர்",
    observed_symptoms: "கண்டறியப்பட்ட நோய் அறிகுறிகள்",
    ai_analysis_report: "விரிவான AI ஆய்வறிக்கை",
    preventive_measures: "தடுப்பு மற்றும் மேலாண்மை முறைகள்",
    treatment_protocol: "பரிந்துரைக்கப்பட்ட சிகிச்சை நெறிமுறை",
    step_label: "படி",
    confidence: "துல்லியம்",

    // Smart SOS & Wildlife Incident Reporting
    sos_banner_badge: "அவசர வனவிலங்கு & பண்ணை ஆபத்து உதவி",
    sos_banner_title: "24/7 உடனடி அவசர உதவி (SOS) & புகார் அளிப்பு",
    sos_banner_desc: "யானை ஊடுருவல், காட்டுப்பன்றி கூட்டம், சிறுத்தை/புலி நடமாட்டம், பாம்புக்கடி அல்லது பயிர் சேதமா? ஜிபிஎஸ் இருப்பிடம் மற்றும் குரல் பதிவோடு வனத்துறை & துரித அதிரடிப்படைக்கு உடனே தகவல் அனுப்புங்கள்.",
    sos_launch_report: "உடனடி அவசர உதவி (SOS)",
    sos_modal_title: "ஸ்மார்ட் அவசர உதவி (SOS) & துரித நடவடிக்கை",
    sos_modal_sub: "வனவிலங்கு மோதல் & அரசு அதிகாரிகளுக்கு நேரடி ஜிபிஎஸ் தகவல் அமைப்பு",
    sos_step1_title: "உங்களுக்கு என்ன வகையான அவசர உதவி தேவை?",
    sos_step1_desc: "அருகிலுள்ள வனச்சரகம் அல்லது மீட்புக் குழுவை எச்சரிக்க விலங்கு அல்லது அவசரப் பிரிவைத் தேர்ந்தெடுக்கவும்.",
    sos_elephant_name: "யானை",
    sos_elephant_tag: "பண்ணை அருகே யானை / பயிர் சேதம் / ஆபத்து",
    sos_wild_boar_name: "காட்டுப்பன்றி",
    sos_wild_boar_tag: "பண்ணை அருகே காட்டுப்பன்றி / பயிர் அழிப்பு",
    sos_monkey_name: "குரங்கு கூட்டம்",
    sos_monkey_tag: "குரங்குகள் ஊடுருவல் / பழத்தோட்ட சேதம்",
    sos_leopard_name: "சிறுத்தை / புலி",
    sos_leopard_tag: "ஆபத்தான பெரும் விலங்கு / உடனடி உயிராபத்து",
    sos_bear_name: "கரடி",
    sos_bear_tag: "கரடி நடமாட்டம் / பண்ணை ஊடுருவல்",
    sos_snake_name: "பாம்பு",
    sos_snake_tag: "விஷப்பாம்பு அவசரநிலை / கடி ஆபத்து",
    sos_other_wildlife_name: "மற்ற வனவிலங்குகள்",
    sos_other_wildlife_tag: "மான், காட்டெருமை அல்லது பிற வனவிலங்கு",
    sos_other_sos_name: "பிற அவசரநிலை",
    sos_other_sos_tag: "தீவிபத்து, மருத்துவம், திருட்டு, பண்ணை ஆபத்து",
    sos_back_animal: "விலங்கு தேர்வுக்கு திரும்புக",
    sos_select_other_title: "பிற அவசரப் பிரிவைத் தேர்ந்தெடுக்கவும்",
    sos_select_other_desc: "தீயணைப்பு, காவல்துறை அல்லது கால்நடை மருத்துவத் துறைக்கு இந்த புகார் உடனே அனுப்பப்படும்.",
    sos_other_fire: "தீ விபத்து",
    sos_other_fire_desc: "பயிர் தீ, வைக்கோல் போர் அல்லது கொட்டகை தீ",
    sos_other_flood: "வெள்ளம் / நீர் பெருக்கெடுப்பு",
    sos_other_flood_desc: "வாய்க்கால் உடைப்பு அல்லது வயலில் வெள்ளம்",
    sos_other_theft: "திருட்டு / பாதுகாப்பு",
    sos_other_theft_desc: "அத்துமீறல் அல்லது விளைபொருட்கள் திருட்டு",
    sos_other_livestock: "கால்நடை அவசரநிலை",
    sos_other_livestock_desc: "காயமடைந்த மாடுகள் அல்லது வெறிநாய் அச்சுறுத்தல்",
    sos_other_human: "மனித உயிருக்கு ஆபத்து",
    sos_other_human_desc: "தொழிலாளி காயம் அல்லது சிக்கிய நிலை",
    sos_other_storm: "புயல் / மரம் சாய்வு",
    sos_other_storm_desc: "மின் கம்பி அறுந்து விழுதல் அல்லது புயல் சேதம்",
    sos_incident_detected: "சம்பவம் கண்டறியப்பட்டது",
    sos_step_verifying: "படி 1/3: ஜிபிஎஸ் & அதிகார வரம்பு சரிபார்ப்பு",
    sos_live_gps: "📍 உங்கள் நேரலை ஜிபிஎஸ் இருப்பிடம்",
    sos_jurisdiction: "🏛️ வன அதிகார வரம்பு: சத்தியமங்கலம் / தாளவாடி வனச்சரகம்",
    sos_resp_authority: "பொறுப்புள்ள அரசு அதிகாரம்",
    sos_authority_desc: "தமிழ்நாடு வனத்துறை • கட்டணமில்லா வனவிலங்கு உதவி எண்: 1800-425-4545 / 1926",
    sos_change_type: "வகையை மாற்றுக",
    sos_confirm_location: "இருப்பிடத்தை உறுதிசெய்து அடுத்து செல்க ➔",
    sos_voice_choice_title: "நடந்ததை வன அலுவலரிடம் குரல் மூலம் கூற விரும்புகிறீர்களா?",
    sos_voice_choice_desc: "உங்கள் தாய்மொழியில் இயல்பாகப் பேசலாம். உங்கள் அசல் குரல் பதிவு நேரடியாக வனத்துறை அதிகாரியை சென்றடையும்.",
    sos_speak_title: "🎤 பேசுங்கள்",
    sos_speak_desc: "நீங்கள் காண்பதை விவரிக்கும் குரல் செய்தியைப் பதிவு செய்யுங்கள். அதிகாரி உங்கள் குரலைக் கேட்பார்.",
    sos_no_voice_title: "➡️ குரல் பதிவு இன்றி தொடர்க",
    sos_no_voice_desc: "குரல் பதிவு செய்யாமல் உங்கள் ஜிபிஎஸ் இருப்பிடம் மற்றும் தகவல்களை உடனடியாக அனுப்புங்கள்.",
    sos_tell_happened: "🎤 என்ன நடந்தது என்று கூறுங்கள்",
    sos_tell_happened_desc: "விலங்கு இருக்கும் இடம், பயிர் சேதம் அல்லது ஆபத்தை விளக்குங்கள். தமிழில் தாராளமாகப் பேசுங்கள்.",
    sos_tap_record: "பதிவு செய்ய மைக்கை தட்டவும்",
    sos_recording_stop: "● பதிவாகிறது... நிறுத்த சதுரத்தை தட்டவும்",
    sos_rec_captured: "✓ குரல் பதிவு செய்யப்பட்டது",
    sos_listen_voice: "குரலைக் கேட்கவும்",
    sos_pause_playback: "நிறுத்தவும்",
    sos_rerecord: "மீண்டும் பதிவு செய்",
    sos_voice_guarantee: "💡 இந்த அசல் குரல் பதிவு நேரடியாக வனத்துறை கள அலுவலருக்கு வழங்கப்படும்.",
    sos_send_with_voice: "குரல் பதிவுடன் எச்சரிக்கை அனுப்புக ➔",
    sos_assessment_title: "விரைவு கள நிலை மதிப்பீடு",
    sos_assessment_desc: "மீட்புக் குழு முன்னுரிமை அளிக்க சில பதில்களைத் தேர்வு செய்யவும்:",
    sos_danger_immediate: "⚠️ மனித உயிருக்கு உடனடி ஆபத்து உள்ளது",
    sos_danger_immediate_sub: "மனிதர்கள் அல்லது குழந்தைகள் அருகில் அச்சுறுத்தலில் உள்ளனர்",
    sos_animal_present: "விலங்கு தற்போது பண்ணைக்குள் உள்ளது",
    sos_animal_present_sub: "வயலில் அல்லது வேலிப் பகுதியில் இப்போது தெரிகிறது",
    sos_damage_ongoing: "பயிர் அல்லது சொத்து சேதம் அடைந்துள்ளது",
    sos_damage_ongoing_sub: "கரும்பு, வாழை, தக்காளி அல்லது சொட்டுநீர் குழாய்கள் சேதம்",
    sos_send_now: "இப்போதே அவசர தகவல் அனுப்புக ➔",
    sos_sent_success: "அவசர தகவல் வெற்றிகரமாக அனுப்பப்பட்டது!",
    sos_incident_ref: "சம்பவ கண்காணிப்பு எண்:",
    sos_type_col: "சம்பவ வகை",
    sos_gps_col: "ஜிபிஎஸ் இடம்",
    sos_voice_col: "குரல் பதிவு",
    sos_status_col: "நிலை",
    sos_transmitted: "✓ அனுப்பப்பட்டது",
    sos_delivered: "✓ சேர்க்கப்பட்டது",
    sos_no_voice: "குரல் பதிவு இல்லை",
    sos_realtime_status: "🚨 நேரலை அதிகாரப்பூர்வ நடவடிக்கை நிலை",
    sos_safety_instructions: "🛡️ உடனடி பாதுகாப்பு வழிகாட்டுதல்கள்:",
    sos_call_authority_btn: "அதிகாரியை அழைக்கவும்",
    sos_done_close: "முடிந்தது & மூடுக",
    sos_safety_elephant: "யானைகளிடமிருந்து குறைந்தது 150 மீட்டர் பாதுகாப்பான தூரத்தில் இருங்கள். அவற்றின் கண்களில் நேராக டார்ச் அடிக்காதீர்கள். பண்ணை விளக்குகளை எரியவிட்டு பாதுகாப்பான கான்கிரீட் கட்டடத்திற்கு செல்லுங்கள்.",
    sos_safety_boar: "காட்டுப்பன்றிகளை மூலையில் மடக்கவோ விரட்டவோ வேண்டாம்; குட்டிகளுடன் உள்ள பன்றிகள் மிக ஆக்ரோஷமாக தாக்கும். வன ரோந்து வரும் வரை கரும்புக்காட்டிற்குள் தனியாக செல்ல வேண்டாம்.",
    sos_safety_leopard: "உடனடி ஆபத்து: குழந்தைகளையும் கால்நடைகளையும் உடனே வீட்டிற்குள் அழைத்துச் செல்லுங்கள். மாட்டுக்கொட்டகையை பூட்டுங்கள். வெளிச்சத்தை எரியவிட்டு வனத்துறையினர் வரும் வரை உள்ளே இருங்கள்.",
    sos_safety_bear: "கரடியைப் பார்த்தால் ஓடாதீர்கள். முதுகைக் காட்டாமல் மெதுவாக பின்வாங்குங்கள். சீரான குரலில் பேசி உங்கள் இருப்பிடத்தை உணர்த்தி அது விலகிச் செல்ல அனுமதியுங்கள்.",
    sos_safety_snake: "பாம்பைப் பிடிக்கவோ கொல்லவோ முயற்சிக்காதீர்கள். கடித்தால், கடித்த பகுதியை இதய நிலைக்குக் கீழே அசையாமல் வைத்து உடனடியாக அரசு மருத்துவமனைக்குச் செல்லுங்கள்.",
    sos_safety_fire: "புகை வரும் திசைக்கு எதிர் திசையில் செல்லுங்கள். மின் இணைப்பை உடனடியாக அணைக்கவும். பாதுகாப்பான தூரத்தில் இருங்கள்.",
    sos_safety_default: "ஆபத்திலிருந்து பாதுகாப்பான தூரத்தில் இருங்கள். வனவிலங்குகளை நெருங்கவோ அச்சுறுத்தவோ வேண்டாம். அரசு அதிகாரிகளின் வருகைக்காக காத்திருக்கவும்."

  },
  te: {
    home: "హోమ్",
    nearby_equipment: "సమీప పరికరాలు",
    list_equipment: "మీ పరికరాలను జాబితా చేయండి",
    nearby_storage: "సమీప నిల్వ & కోల్డ్ స్టోరేజ్",
    list_storage: "నిల్వ సౌకర్యాన్ని నమోదు చేయండి",
    shared_transport: "షేర్డ్ రవాణా",
    weather: "వాతావరణం",
    community: "కమ్యూనిటీ",
    market: "మార్కెట్",
    expert_qa: "నిపుణుల Q&A",
    notifications: "నోటిఫికేషన్లు",
    profile: "ప్రొఫైల్",
    good_morning: "శుభోదయం",
    your_farm_dashboard: "మీ ఫామ్ డాష్‌బోర్డ్",
    weather_overview: "వాతావరణ అవలోకనం",
    current_conditions: "ప్రస్తుత పరిస్థితులు",
    actionable_advisories: "చర్యలు",
    seven_day_forecast: "7 రోజుల సూచన",
    login_to_farmogram: "లాగిన్",
    mobile_number: "మొబైల్ నంబర్",
    password: "పాస్వర్డ్",
    register_your_farm: "మీ పొలాన్ని నమోదు చేసుకోండి",
    farmer_onboarding: "రైతు నమోదు",
    full_name: "రైతు పూర్తి పేరు",
    next: "తరువాత",
    back: "వెనుకకు",
    create_password: "పాస్వర్డ్ సృష్టించండి",
    confirm_password: "పాస్వర్డ్ నిర్ధారించండి",
    select_language: "భాషను ఎంచుకోండి",
    state: "రాష్ట్రం",
    district: "జిల్లా",
    land_acres: "సాగు భూమి (ఎకరాలు)",
    soil_type: "మట్టి రకం",
    primary_crops: "పండించే ప్రధాన పంటలు",
    create_profile: "ప్రొఫైల్ సృష్టించండి",
    select_state: "రాష్ట్రాన్ని ఎంచుకోండి",
    select_district: "జిల్లాను ఎంచుకోండి",
    select_soil: "మట్టి రకాన్ని ఎంచుకోండి",
    search: "శోధించండి...",
    recommended_for_you: "మీ కోసం సిఫార్సు చేయబడినవి",
    market_prices: "మార్కెట్ ధరలు",
    disease_detection: "వ్యాధి గుర్తింపు",
    irrigation: "నీటిపారుదల",
    settings: "సెట్టింగులు",
    admin_view: "అడ్మిన్ వీక్షణ",
    farmer_view: "రైతు వీక్షణ",
    profit: "లాభం",
    schemes: "పథకాలు",
    qa: "ప్రశ్నోత్తరాలు",
    smart_agri_decision: "స్మార్ట్ అగ్రి నిర్ణయం & సంఘం",
    main_navigation: "ప్రధాన నావిగేషన్",
    management: "నిర్వహణ",
    settings_subtitle: "ప్రాధాన్యతలను నిర్వహించండి",
    language_region: "భాష & ప్రాంతం",
    app_language: "యాప్ భాష",
    select_pref_lang: "ప్రాధాన్య భాషను ఎంచుకోండి",
    push_notifications: "నోటిఫికేషన్‌లు",
    receive_alerts: "వాతావరణ హెచ్చరికలను స్వీకరించండి",
    accessibility: "సౌలభ్యం",
    high_contrast: "అధిక కాంట్రాస్ట్ మోడ్",
    increase_contrast: "చదవడానికి సులభంగా ఉండేలా మార్చండి",
    about_farmogram: "ఫార్మోగ్రామ్ గురించి",
    version_info: "వెర్షన్ 1.0.0 (SIH 2026 ప్రోటోటైప్)"
,

    location: "స్థానం:",
    temperature: "ఉష్ణోగ్రత:",
    primary_soil: "ప్రాథమిక మట్టి:",
    active_crops_in_season: "సీజన్‌లో క్రియాశీల పంటలు",
    agricultural_advisory: "వ్యవసాయ సలహా:",
    high_priority: "అధిక ప్రాధాన్యత",
    view_weather_advisory: "వాతావరణ సలహాను చూడండి",
    decision_support_tools: "నిర్ణయ మద్దతు సాధనాలు",
    pre_sowing_intelligence: "విత్తనాల నుండి కోత వరకు మేధస్సు",
    crop_advisor_desc: "AI బహుళ-కారకాల వ్యవసాయ సలహా",
    high_precision: "అధిక ఖచ్చితత్వం",
    weather_advisory: "వాతావరణ సలహా",
    weather_advisory_desc: "7-రోజుల సూక్ష్మవాతావరణ అంచనా",
    rain_alert: "వర్షం హెచ్చరిక",
    disease_desc: "నివారణల కోసం ఆకు గాయాలను స్కాన్ చేయండి",
    instant_ai: "తక్షణ AI",
    irrigation_desc: "వాతావరణం & దశ ఆధారిత షెడ్యూల్",
    water_saving: "నీటి పొదుపు",
    market_prices_desc: "లైవ్ మండి ధరలు",
    tomato_up: "టొమాటో ↑ 8%",
    profit_calculator: "లాభం కాలిక్యులేటర్",
    profit_desc: "ఖర్చులు, దిగుబడి & ROI లెక్కించండి",
    financials: "ఆర్థికపరమైనవి",
    open_tool: "సాధనం తెరవండి",
    community_hub_title: "🌾 ఫార్మోగ్రామ్ సంఘం & నాలెడ్జ్ హబ్",
    community_hub_subtitle: "భారతీయ రైతుల నిజమైన అనుభవాలు & ధృవీకరించబడిన సలహాలు",
    share_experience: "మీ అనుభవాన్ని పంచుకోండి",
    // Tools & Actions
    crop_advisor: "పంట సలహాదారు",
    transport_pooling: "షేర్డ్ రవాణా పూలింగ్",
    transport_pooling_desc: "మార్కెట్‌కు వెళ్లే సమీప రైతులతో వాహనాన్ని పంచుకోండి మరియు ఖర్చులను తగ్గించుకోండి.",
    save_money: "₹800+ ఆదా",
    connect_agronomist: "వ్యవసాయ అధికారితో మాట్లాడండి",
    ready_scan: "వ్యాధి నిర్ధారణకు సిద్ధంగా ఉంది",
    ready_scan_desc: "'పంట వ్యాధిని విశ్లేషించండి' క్లిక్ చేసి సమగ్ర లక్షణాలు, సేంద్రీయ మరియు రసాయన నివారణలను చూడండి.",
    upload_leaf_photo: "సోకిన ఆకు ఫోటోను అప్‌లోడ్ చేయండి",
    upload_leaf_sub: "మచ్చలు లేదా రంగు మారిన ఆకుల దగ్గరి ఫోటో తీయండి.",
    drag_drop_leaf: "ఆకు చిత్రాన్ని అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి",
    png_jpg_max: "PNG, JPG, JPEG గరిష్టంగా 10MB",
    replace_image: "చిత్రాన్ని మార్చండి",
    scanning_morphology: "ఆకు నిర్మాణాన్ని స్కాన్ చేస్తోంది...",
    analyzing_engine: "AI ఇంజిన్ విశ్లేషిస్తోంది...",
    analyze_crop_disease: "పంట వ్యాధిని విశ్లేషించండి",
    detected_crop: "గుర్తించిన పంట",
    observed_symptoms: "గమనించిన వ్యాధి లక్షణాలు",
    ai_analysis_report: "సమగ్ర AI విశ్లేషణ నివేదిక",
    preventive_measures: "నివారణ మరియు నిర్వహణ చర్యలు",
    treatment_protocol: "సిఫార్సు చేసిన చికిత్స ప్రోటోకాల్",
    step_label: "దశ",
    confidence: "ఖచ్చితత్వం",

    // Smart SOS & Wildlife Incident Reporting
    sos_banner_badge: "అత్యవసర వన్యప్రాణి & వ్యవసాయ రక్షణ డిస్పాచ్",
    sos_banner_title: "24/7 స్మార్ట్ SOS & సంఘటన రిపోర్టింగ్",
    sos_banner_desc: "ఏనుగులు రావడం, అడవి పందుల గుంపు, చిరుత/పులి సంచారం, పాము కాటు లేదా పంట ధ్వంసమా? GPS లొకేషన్ మరియు వాయిస్ నోట్‌తో అటవీ శాఖ మరియు రెస్క్యూ బృందాన్ని వెంటనే అప్రమత్తం చేయండి.",
    sos_launch_report: "అత్యవసర అలర్ట్ పంపండి (SOS)",
    sos_modal_title: "స్మార్ట్ SOS & అత్యవసర డిస్పాచ్",
    sos_modal_sub: "వన్యప్రాణి సంఘర్షణ & ప్రభుత్వ అధికారులకు తక్షణ GPS రూటింగ్",
    sos_step1_title: "మీకు ఎలాంటి అత్యవసర సహాయం కావాలి?",
    sos_step1_desc: "సమీప అటవీ రేంజ్ లేదా రెస్క్యూ అథారిటీని అప్రమత్తం చేయడానికి జంతువు లేదా అత్యవసర వర్గాన్ని ఎంచుకోండి.",
    sos_elephant_name: "ఏనుగు",
    sos_elephant_tag: "పొలం వద్ద ఏనుగు / పంట నష్టం / ప్రమాదం",
    sos_wild_boar_name: "అడవి పంది",
    sos_wild_boar_tag: "పొలం వద్ద అడవి పందులు / పంట నష్టం",
    sos_monkey_name: "కోతుల గుంపు",
    sos_monkey_tag: "తోటల పై కోతుల దాడి / నష్టం",
    sos_leopard_name: "చిరుత / పులి",
    sos_leopard_tag: "ప్రమాదకరమైన పెద్ద జంతువు / ప్రాణాపాయం",
    sos_bear_name: "ఎలుగుబంటి",
    sos_bear_tag: "ఎలుగుబంటి సంచారం / పొలంలోకి రావడం",
    sos_snake_name: "పాము",
    sos_snake_tag: "విషపూరిత పాము / కాటు ప్రమాదం",
    sos_other_wildlife_name: "ఇతర వన్యప్రాణులు",
    sos_other_wildlife_tag: "జింక, అడవి దున్న లేదా ఇతర జంతువులు",
    sos_other_sos_name: "ఇతర అత్యవసరాలు",
    sos_other_sos_tag: "అగ్నిప్రమాదం, వైద్యం, దొంగతనం, విపత్తు",
    sos_back_animal: "జంతువుల ఎంపికకు తిరిగి వెళ్లండి",
    sos_select_other_title: "ఇతర అత్యవసర వర్గాన్ని ఎంచుకోండి",
    sos_select_other_desc: "ఈ నివేదిక స్థానిక అగ్నిమాపక, పోలీస్ లేదా పశువైద్య విభాగానికి పంపబడుతుంది.",
    sos_other_fire: "అగ్నిప్రమాదం",
    sos_other_fire_desc: "పంటకు మంటలు, పశువుల పాక లేదా గడ్డివాము కాలిపోవడం",
    sos_other_flood: "వరద / నీరు ముంచెత్తడం",
    sos_other_flood_desc: "కాలువ గండి లేదా పొలంలో నీరు చేరడం",
    sos_other_theft: "దొంగతనం / భద్రత",
    sos_other_theft_desc: "అక్రమ ప్రవేశం లేదా ఉత్పత్తుల దొంగతనం",
    sos_other_livestock: "పశువుల అత్యవసరం",
    sos_other_livestock_desc: "గాయపడిన పశువులు, పిచ్చికుక్కల ముప్పు",
    sos_other_human: "మానవ భద్రత ముప్పు",
    sos_other_human_desc: "రైతు/కూలీ గాయపడటం లేదా చిక్కుకుపోవడం",
    sos_other_storm: "తుఫాను / చెట్లు కూలడం",
    sos_other_storm_desc: "కరెంట్ వైర్లు తెగిపడటం లేదా తుఫాను నష్టం",
    sos_incident_detected: "సంఘటన గుర్తించబడింది",
    sos_step_verifying: "దశ 1/3: GPS & అధికార పరిధి ధృవీకరణ",
    sos_live_gps: "📍 మీ ప్రత్యక్ష GPS స్థానం",
    sos_jurisdiction: "🏛️ అటవీ పరిధి: సత్యమంగళం / ఈరోడ్ డివిజన్",
    sos_resp_authority: "బాధ్యతాయుత ప్రభుత్వ అధికారం",
    sos_authority_desc: "తమిళనాడు అటవీ శాఖ • టోల్-ఫ్రీ వన్యప్రాణి హెల్ప్‌లైన్: 1800-425-4545 / 1926",
    sos_change_type: "రకం మార్చండి",
    sos_confirm_location: "స్థానాన్ని నిర్ధారించి ముందుకు వెళ్ళండి ➔",
    sos_voice_choice_title: "ఏమి జరిగిందో అధికారికి వాయిస్ ద్వారా చెప్పాలనుకుంటున్నారా?",
    sos_voice_choice_desc: "మీరు మీ మాతృభాషలో సహజంగా మాట్లాడవచ్చు. మీ అసలు రికార్డింగ్ నేరుగా అధికారికి చేరుతుంది.",
    sos_speak_title: "🎤 మాట్లాడండి",
    sos_speak_desc: "పరిస్థితిని వివరిస్తూ వాయిస్ రికార్డ్ చేయండి. అధికారి మీ మాటలను వింటారు.",
    sos_no_voice_title: "➡️ వాయిస్ లేకుండా కొనసాగించండి",
    sos_no_voice_desc: "వాయిస్ రికార్డ్ చేయకుండా వెంటనే మీ GPS స్థానం మరియు వివరాలను పంపండి.",
    sos_tell_happened: "🎤 ఏమి జరిగిందో చెప్పండి",
    sos_tell_happened_desc: "జంతువు ఉన్న స్థానం, పంట నష్టం లేదా ప్రమాదాన్ని వివరించండి. ధైర్యంగా మాట్లాడండి.",
    sos_tap_record: "రికార్డింగ్ ప్రారంభించడానికి మైక్ నొక్కండి",
    sos_recording_stop: "● రికార్డ్ అవుతోంది... ఆపడానికి చతురస్రాన్ని నొక్కండి",
    sos_rec_captured: "✓ వాయిస్ రికార్డింగ్ పూర్తయింది",
    sos_listen_voice: "వాయిస్ వినండి",
    sos_pause_playback: "ఆపండి",
    sos_rerecord: "మళ్ళీ రికార్డ్ చేయండి",
    sos_voice_guarantee: "💡 ఈ అసలు వాయిస్ రికార్డింగ్ నేరుగా అటవీ డ్యూటీ అధికారికి చేరుతుంది.",
    sos_send_with_voice: "వాయిస్ నోట్‌తో SOS పంపండి ➔",
    sos_assessment_title: "త్వరిత పరిస్థితుల అంచనా",
    sos_assessment_desc: "రెస్క్యూ బృందం ప్రాధాన్యతను నిర్ణయించడానికి సమాధానాలను ఎంచుకోండి:",
    sos_danger_immediate: "⚠️ ప్రాణాలకు తక్షణ ప్రమాదం ఉంది",
    sos_danger_immediate_sub: "ప్రజలు లేదా పిల్లలు సమీపంలో ప్రమాదంలో ఉన్నారు",
    sos_animal_present: "జంతువు ప్రస్తుతం పొలంలోనే ఉంది",
    sos_animal_present_sub: "పొలంలో లేదా సరిహద్దులో ప్రస్తుతం కనిపిస్తోంది",
    sos_damage_ongoing: "పంట లేదా ఆస్తులకు నష్టం జరిగింది",
    sos_damage_ongoing_sub: "చెరకు, అరటి, టమోటా లేదా డ్రిప్ పైపులు ధ్వంసం",
    sos_send_now: "ఇప్పుడే SOS పంపండి ➔",
    sos_sent_success: "SOS విజయవంతంగా పంపబడింది!",
    sos_incident_ref: "అత్యవసర రిఫరెన్స్ సంఖ్య:",
    sos_type_col: "సంఘటన రకం",
    sos_gps_col: "GPS స్థానం",
    sos_voice_col: "వాయిస్ సందేశం",
    sos_status_col: "స్థితి",
    sos_transmitted: "✓ పంపబడింది",
    sos_delivered: "✓ చేరింది",
    sos_no_voice: "వాయిస్ లేదు",
    sos_realtime_status: "🚨 ప్రత్యక్ష కార్యాచరణ స్థితి",
    sos_safety_instructions: "🛡️ తక్షణ భద్రతా సూచనలు:",
    sos_call_authority_btn: "అధికారికి కాల్ చేయండి",
    sos_done_close: "పూర్తయింది & మూసివేయండి",
    sos_safety_elephant: "ఏనుగుల నుండి కనీసం 150 మీటర్ల సురక్షిత దూరం పాటించండి. వాటి కళ్ళపై లైట్లు వేయకండి. లైట్లు వేసి సురక్షితమైన భవనంలో ఉండండి.",
    sos_safety_boar: "అడవి పందులను తరుముకోవద్దు; పిల్లలున్న పందులు దూకుడుగా దాడి చేయవచ్చు. దట్టమైన పంటల్లోకి ఒంటరిగా వెళ్ళకండి.",
    sos_safety_leopard: "తక్షణ ప్రమాదం: పిల్లలను మరియు పశువులను వెంటనే సురక్షిత ప్రదేశానికి తరలించండి. పాకలను మూసివేసి ఇంట్లోనే ఉండండి.",
    sos_safety_bear: "ఎలుగుబంటిని చూస్తే పరుగెత్తవద్దు. వెనక్కి తిరిగి చూడకుండా నెమ్మదిగా వెనక్కి వెళ్ళండి. ప్రశాంతంగా మాట్లాడి దాన్ని వెళ్ళనివ్వండి.",
    sos_safety_snake: "పామును పట్టుకోవడానికి లేదా చంపడానికి ప్రయత్నించవద్దు. కాటు వేస్తే గాయాన్ని గుండె స్థాయి కంటే కింద ఉంచి వెంటనే ఆసుపత్రికి వెళ్ళండి.",
    sos_safety_fire: "పొగ వచ్చే దిశ నుండి దూరంగా వెళ్ళండి. విద్యుత్ సరఫరా ఆపివేసి సురక్షితంగా ఉండండి.",
    sos_safety_default: "ప్రమాదం నుండి సురక్షిత దూరంలో ఉండండి. వన్యప్రాణులను రెచ్చగొట్టవద్దు మరియు ప్రభుత్వ సహాయం కోసం వేచి ఉండండి.",

    // Crops & Soils
    "Paddy": "వరి",
    "Tomato": "టమోటా",
    "Groundnut": "వేరుశనగ",
    "Sugarcane": "చెరకు",
    "Cotton": "పత్తి",
    "Banana": "అరటి",
    "Maize": "మొక్కజొన్న",
    "Turmeric": "పసుపు",
    "Red Loam": "ఎర్ర నేలలు",
    "Clayey Alluvial": "బంకమట్టి ఒండ్రు నేల",
    "Black Cotton Soil (Regur)": "నల్ల రేగడి నేల",
    "Sandy Loam": "ఇసుక నేల",
    "Laterite Soil": "లాటరైట్ నేల"
  },
  kn: {
    home: "ಮುಖಪುಟ",
    nearby_equipment: "ಹತ್ತಿರದ ಉಪಕರಣಗಳು",
    list_equipment: "ನಿಮ್ಮ ಉಪಕರಣವನ್ನು ಬಾಡಿಗೆಗೆ ನೀಡಿ",
    nearby_storage: "ಹತ್ತಿರದ ಶೇಖರಣೆ & ಕೋಲ್ಡ್ ಸ್ಟೋರೇಜ್",
    list_storage: "ಶೇಖರಣಾ ಸೌಲಭ್ಯವನ್ನು ನೋಂದಾಯಿಸಿ",
    shared_transport: "ಹಂಚಿಕೆಯ ಸಾರಿಗೆ",
    weather: "ಹವಾಮಾನ",
    community: "ಸಮುದಾಯ",
    market: "ಮಾರುಕಟ್ಟೆ",
    expert_qa: "ತಜ್ಞರ ಪ್ರಶ್ನೋತ್ತರ",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    good_morning: "ಶುಭೋದಯ",
    your_farm_dashboard: "ನಿಮ್ಮ ಫಾರ್ಮ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    weather_overview: "ಹವಾಮಾನ ಅವಲೋಕನ",
    current_conditions: "ಪ್ರಸ್ತುತ ಪರಿಸ್ಥಿತಿಗಳು",
    actionable_advisories: "ಸಲಹೆಗಳು",
    seven_day_forecast: "7-ದಿನದ ಮುನ್ಸೂಚನೆ",
    login_to_farmogram: "ಲಾಗಿನ್ ಮಾಡಿ",
    mobile_number: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    password: "ಪಾಸ್ವರ್ಡ್",
    register_your_farm: "ನೋಂದಾಯಿಸಿ",
    farmer_onboarding: "ರೈತರ ನೋಂದಣಿ",
    full_name: "ರೈತರ ಪೂರ್ಣ ಹೆಸರು",
    next: "ಮುಂದೆ",
    back: "ಹಿಂದೆ",
    create_password: "ಪಾಸ್ವರ್ಡ್ ರಚಿಸಿ",
    confirm_password: "ಪಾಸ್ವರ್ಡ್ ಖಚಿತಪಡಿಸಿ",
    select_language: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    state: "ರಾಜ್ಯ",
    district: "ಜಿಲ್ಲೆ",
    land_acres: "ಕೃಷಿ ಭೂಮಿ (ಎಕರೆ)",
    soil_type: "ಮಣ್ಣಿನ ಪ್ರಕಾರ",
    primary_crops: "ಮುಖ್ಯ ಬೆಳೆಗಳು",
    create_profile: "ಪ್ರೊಫೈಲ್ ರಚಿಸಿ",
    select_state: "ರಾಜ್ಯವನ್ನು ಆರಿಸಿ",
    select_district: "ಜಿಲ್ಲೆಯನ್ನು ಆರಿಸಿ",
    select_soil: "ಮಣ್ಣಿನ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ",
    search: "ಹುಡುಕಿ...",
    recommended_for_you: "ನಿಮಗಾಗಿ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ",
    market_prices: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು",
    disease_detection: "ರೋಗ ಪತ್ತೆ",
    irrigation: "ನೀರಾವರಿ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    admin_view: "ನಿರ್ವಾಹಕ ವೀಕ್ಷಣೆ",
    farmer_view: "ರೈತ ವೀಕ್ಷಣೆ",
    profit: "ಲಾಭ",
    schemes: "ಯೋಜನೆಗಳು",
    qa: "ಪ್ರಶ್ನೋತ್ತರ",
    smart_agri_decision: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ನಿರ್ಧಾರ ಮತ್ತು ಸಮುದಾಯ",
    main_navigation: "ಮುಖ್ಯ ಸಂಚರಣೆ",
    management: "ನಿರ್ವಹಣೆ",
    settings_subtitle: "ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    language_region: "ಭಾಷೆ ಮತ್ತು ಪ್ರದೇಶ",
    app_language: "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ",
    select_pref_lang: "ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    push_notifications: "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು",
    receive_alerts: "ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ",
    accessibility: "ಪ್ರವೇಶಿಸುವಿಕೆ",
    high_contrast: "ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್ ಮೋಡ್",
    increase_contrast: "ಓದಲು ಸುಲಭವಾಗುವಂತೆ ಮಾಡಿ",
    about_farmogram: "ಫಾರ್ಮೋಗ್ರಾಮ್ ಬಗ್ಗೆ",
    version_info: "ಆವೃತ್ತಿ 1.0.0 (SIH 2026 ಪ್ರೋಟೋಟೈಪ್)"
,

    location: "ಸ್ಥಳ:",
    temperature: "ತಾಪಮಾನ:",
    primary_soil: "ಪ್ರಾಥಮಿಕ ಮಣ್ಣು:",
    active_crops_in_season: "ಋತುವಿನಲ್ಲಿ ಸಕ್ರಿಯ ಬೆಳೆಗಳು",
    agricultural_advisory: "ಕೃಷಿ ಸಲಹೆ:",
    high_priority: "ಹೆಚ್ಚಿನ ಆದ್ಯತೆ",
    view_weather_advisory: "ಹವಾಮಾನ ಸಲಹೆ ವೀಕ್ಷಿಸಿ",
    decision_support_tools: "ನಿರ್ಧಾರ ಬೆಂಬಲ ಪರಿಕರಗಳು",
    pre_sowing_intelligence: "ಬಿತ್ತನೆ ಮೊದಲು ಕಟಾವಿನವರೆಗೆ ಗುಪ್ತಚರ",
    crop_advisor_desc: "AI ಬಹು-ಅಂಶ ಕೃಷಿ ಸಲಹೆ",
    high_precision: "ಹೆಚ್ಚಿನ ನಿಖರತೆ",
    weather_advisory: "ಹವಾಮಾನ ಸಲಹೆ",
    weather_advisory_desc: "7-ದಿನದ ಸೂಕ್ಷ್ಮ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",
    rain_alert: "ಮಳೆ ಎಚ್ಚರಿಕೆ",
    disease_desc: "ಪರಿಹಾರಕ್ಕಾಗಿ ಎಲೆಗಳ ಗಾಯಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    instant_ai: "ತತ್ಕ್ಷಣದ AI",
    irrigation_desc: "ಹವಾಮಾನ ಮತ್ತು ಹಂತ-ಆಧಾರಿತ ವೇಳಾಪಟ್ಟಿ",
    water_saving: "ನೀರು ಉಳಿತಾಯ",
    market_prices_desc: "ಲೈವ್ ಮಂಡಿ ದರಗಳು",
    tomato_up: "ಟೊಮೆಟೊ ↑ 8%",
    profit_calculator: "ಲಾಭ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    profit_desc: "ವೆಚ್ಚಗಳು, ಇಳುವರಿ ಮತ್ತು ROI",
    financials: "ಹಣಕಾಸು",
    open_tool: "ಪರಿಕರ ತೆರೆಯಿರಿ",
    community_hub_title: "🌾 ಫಾರ್ಮೋಗ್ರಾಮ್ ಸಮುದಾಯ ಮತ್ತು ಜ್ಞಾನ ಕೇಂದ್ರ",
    community_hub_subtitle: "ಭಾರತೀಯ ರೈತರ ನೈಜ ಅನುಭವಗಳು ಮತ್ತು ಪರಿಶೀಲಿಸಿದ ಸಲಹೆಗಳು",
    share_experience: "ನಿಮ್ಮ ಅನುಭವ ಹಂಚಿಕೊಳ್ಳಿ",
    // Tools & Actions
    crop_advisor: "ಬೆಳೆ ಸಲಹೆಗಾರ",
    transport_pooling: "ಹಂಚಿಕೆಯ ಸಾರಿಗೆ ಪೂಲಿಂಗ್",
    transport_pooling_desc: "ಮಾರುಕಟ್ಟೆಗೆ ತೆರಳುವ ಹತ್ತಿರದ ರೈತರೊಂದಿಗೆ ವಾಹನ ಹಂಚಿಕೊಳ್ಳಿ ಮತ್ತು ವೆಚ್ಚ ಉಳಿಸಿ.",
    save_money: "₹800+ ಉಳಿತಾಯ",
    connect_agronomist: "ಕೃಷಿ ಅಧಿಕಾರಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ",
    ready_scan: "ರೋಗ ಪರೀಕ್ಷೆಗೆ ಸಿದ್ಧವಾಗಿದೆ",
    ready_scan_desc: "'ಬೆಳೆ ರೋಗವನ್ನು ವಿಶ್ಲೇಷಿಸಿ' ಕ್ಲಿಕ್ ಮಾಡಿ ಮತ್ತು ಸಮಗ್ರ ಲಕ್ಷಣಗಳು, ಜೈವಿಕ ಪರಿಹಾರಗಳು ಮತ್ತು ರಾಸಾಯನಿಕ ನಿಯಂತ್ರಣಗಳನ್ನು ವೀಕ್ಷಿಸಿ.",
    upload_leaf_photo: "ಬಾಧಿತ ಎಲೆಯ ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    upload_leaf_sub: "ಚುಕ್ಕೆಗಳು ಅಥವಾ ಬಣ್ಣ ಬದಲಾವಣೆಯಿರುವ ಎಲೆಗಳ ನಿಕಟ ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ.",
    drag_drop_leaf: "ಎಲೆಯ ಚಿತ್ರವನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
    png_jpg_max: "PNG, JPG, JPEG ಗರಿಷ್ಠ 10MB",
    replace_image: "ಚಿತ್ರವನ್ನು ಬದಲಾಯಿಸಿ",
    scanning_morphology: "ಎಲೆಯ ರಚನೆಯನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    analyzing_engine: "AI ಎಂಜಿನ್ ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    analyze_crop_disease: "ಬೆಳೆ ರೋಗವನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
    detected_crop: "ಗುರುತಿಸಲಾದ ಬೆಳೆ",
    observed_symptoms: "ಕಂಡುಬಂದ ರೋಗ ಲಕ್ಷಣಗಳು",
    ai_analysis_report: "ವಿವರವಾದ AI ವಿಶ್ಲೇಷಣಾ ವರದಿ",
    preventive_measures: "ತಡೆಗಟ್ಟುವ ಕ್ರಮಗಳು",
    treatment_protocol: "ಶಿಫಾರಸು ಮಾಡಿದ ಚಿಕಿತ್ಸಾ ಪ್ರೋಟೋಕಾಲ್",
    step_label: "ಹಂತ",
    confidence: "ನಿಖರತೆ",

    // Smart SOS & Wildlife Incident Reporting
    sos_banner_badge: "ತುರ್ತು ವನ್ಯಜೀವಿ ಮತ್ತು ಕೃಷಿ ರಕ್ಷಣಾ ರವಾನೆ",
    sos_banner_title: "24/7 ಸ್ಮಾರ್ಟ್ SOS & ಘಟನಾ ವರದಿ",
    sos_banner_desc: "ಆನೆಗಳ ದಾಳಿ, ಕಾಡುಹಂದಿಗಳ ಹಿಂಡು, ಚಿರತೆ/ಹುಲಿ ಚಲನವಲನ, ಹಾವು ಕಡಿತ ಅಥವಾ ಬೆಳೆ ಹಾನಿಯೇ? ಜಿಪಿಎಸ್ ಸ್ಥಳ ಮತ್ತು ಧ್ವನಿ ಸಂದೇಶದೊಂದಿಗೆ ಅರಣ್ಯ ಇಲಾಖೆ ಹಾಗೂ ರಕ್ಷಣಾ ತಂಡವನ್ನು ತಕ್ಷಣ ಎಚ್ಚರಿಸಿ.",
    sos_launch_report: "ತುರ್ತು ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಿ (SOS)",
    sos_modal_title: "ಸ್ಮಾರ್ಟ್ SOS ಮತ್ತು ತುರ್ತು ರವಾನೆ",
    sos_modal_sub: "ವನ್ಯಜೀವಿ ಸಂಘರ್ಷ ಮತ್ತು ಸರ್ಕಾರಿ ಪ್ರಾಧಿಕಾರಗಳಿಗೆ ತ್ವರಿತ ಜಿಪಿಎಸ್ ರವಾನೆ",
    sos_step1_title: "ನಿಮಗೆ ಯಾವ ರೀತಿಯ ತುರ್ತು ಸಹಾಯ ಬೇಕು?",
    sos_step1_desc: "ಹತ್ತಿರದ ಅರಣ್ಯ ವಲಯ ಅಥವಾ ರಕ್ಷಣಾ ತಂಡವನ್ನು ಎಚ್ಚರಿಸಲು ವನ್ಯಜೀವಿ ಅಥವಾ ತುರ್ತು ವಿಭಾಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    sos_elephant_name: "ಆನೆ",
    sos_elephant_tag: "ತೋಟದ ಬಳಿ ಆನೆ / ಬೆಳೆ ಹಾನಿ / ಅಪಾಯ",
    sos_wild_boar_name: "ಕಾಡುಹಂದಿ",
    sos_wild_boar_tag: "ತೋಟದ ಬಳಿ ಕಾಡುಹಂದಿಗಳು / ಬೆಳೆ ಹಾನಿ",
    sos_monkey_name: "ಕೋತಿಗಳ ಹಿಂಡು",
    sos_monkey_tag: "ಕೋತಿಗಳ ಹಾವಳಿ / ತೋಟದ ಹಾನಿ",
    sos_leopard_name: "ಚಿರತೆ / ಹುಲಿ",
    sos_leopard_tag: "ಅಪಾಯಕಾರಿ ಪ್ರಾಣಿ / ಪ್ರಾಣಾಪಾಯ",
    sos_bear_name: "ಕರಡಿ",
    sos_bear_tag: "ಕರಡಿ ಸಂಚಾರ / ತೋಟದೊಳಗೆ ಪ್ರವೇಶ",
    sos_snake_name: "ಹಾವು",
    sos_snake_tag: "ವಿಷಪೂರಿತ ಹಾವು / ಕಡಿತದ ಅಪಾಯ",
    sos_other_wildlife_name: "ಇತರ ವನ್ಯಜೀವಿಗಳು",
    sos_other_wildlife_tag: "ಜಿಂಕೆ, ಕಾಡೆಮ್ಮೆ ಅಥವಾ ಇತರ ಕಾಡು ಪ್ರಾಣಿಗಳು",
    sos_other_sos_name: "ಇತರ ತುರ್ತುಸ್ಥಿತಿ",
    sos_other_sos_tag: "ಬೆಂಕಿ, ವೈದ್ಯಕೀಯ, ಕಳ್ಳತನ, ಕೃಷಿ ವಿಪತ್ತು",
    sos_back_animal: "ವನ್ಯಜೀವಿಗಳ ಆಯ್ಕೆಗೆ ಹಿಂತಿರುಗಿ",
    sos_select_other_title: "ಇತರ ತುರ್ತು ವಿಭಾಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    sos_select_other_desc: "ಈ ವರದಿಯನ್ನು ಸ್ಥಳೀಯ ಅಗ್ನಿಶಾಮಕ, ಪೊಲೀಸ್ ಅಥವಾ ಪಶುವೈದ್ಯಕೀಯ ಇಲಾಖೆಗೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ.",
    sos_other_fire: "ಬೆಂಕಿ ಅವಘಡ",
    sos_other_fire_desc: "ಬೆಳೆಗೆ ಬೆಂಕಿ, ಕೊಟ್ಟಿಗೆ ಅಥವಾ ಹುಲ್ಲಿನ ಬಣವೆಗೆ ಬೆಂಕಿ",
    sos_other_flood: "ಪ್ರವಾಹ / ಜಲಾವೃತ",
    sos_other_flood_desc: "ಕಾಲುವೆ ಒಡೆಯುವುದು ಅಥವಾ ಗದ್ದೆಗೆ ನೀರು ನುಗ್ಗುವುದು",
    sos_other_theft: "ಕಳ್ಳತನ / ಭದ್ರತೆ",
    sos_other_theft_desc: "ಅನಧಿಕೃತ ಪ್ರವೇಶ ಅಥವಾ ಕೃಷಿ ಉತ್ಪನ್ನಗಳ ಕಳ್ಳತನ",
    sos_other_livestock: "ಜಾನುವಾರು ತುರ್ತುಸ್ಥಿತಿ",
    sos_other_livestock_desc: "ಗಾಯಗೊಂಡ ದನಕರುಗಳು, ರೇಬೀಸ್ ಅಪಾಯ",
    sos_other_human: "ಮಾನವ ಜೀವಕ್ಕೆ ಅಪಾಯ",
    sos_other_human_desc: "ಕಾರ್ಮಿಕರು ಗಾಯಗೊಂಡಿರುವುದು ಅಥವಾ ಸಿಲುಕಿರುವುದು",
    sos_other_storm: "ಬಿರುಗಾಳಿ / ಮರ ಉರುಳುವುದು",
    sos_other_storm_desc: "ವಿದ್ಯುತ್ ತಂತಿ ತುಂಡಾಗುವುದು ಅಥವಾ ಬಿರುಗಾಳಿ ಹಾನಿ",
    sos_incident_detected: "ಘಟನೆ ಪತ್ತೆಯಾಗಿದೆ",
    sos_step_verifying: "ಹಂತ 1/3: ಜಿಪಿಎಸ್ ಮತ್ತು ಅಧಿಕಾರ ವ್ಯಾಪ್ತಿ ಪರಿಶೀಲನೆ",
    sos_live_gps: "📍 ನಿಮ್ಮ ಲೈವ್ ಜಿಪಿಎಸ್ ಸ್ಥಳ",
    sos_jurisdiction: "🏛️ ಅರಣ್ಯ ವ್ಯಾಪ್ತಿ: ಸತ್ಯಮಂಗಲಂ / ಈರೋಡ್ ವಲಯ",
    sos_resp_authority: "ಜವಾಬ್ದಾರಿಯುತ ಸರ್ಕಾರಿ ಪ್ರಾಧಿಕಾರ",
    sos_authority_desc: "ತಮಿಳುನಾಡು ಅರಣ್ಯ ಇಲಾಖೆ • ಟೋಲ್-ಫ್ರೀ ವನ್ಯಜೀವಿ ಸಹಾಯವಾಣಿ: 1800-425-4545 / 1926",
    sos_change_type: "ವಿಧವನ್ನು ಬದಲಾಯಿಸಿ",
    sos_confirm_location: "ಸ್ಥಳವನ್ನು ದೃಢೀಕರಿಸಿ ಮುಂದುವರಿಯಿರಿ ➔",
    sos_voice_choice_title: "ಅಧಿಕಾರಿಗೆ ಧ್ವನಿಯ ಮೂಲಕ ಏನು ಸಂಭವಿಸಿದೆ ಎಂದು ತಿಳಿಸಲು ಬಯಸುವಿರಾ?",
    sos_voice_choice_desc: "ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ನೀವು ಸಹಜವಾಗಿ ಮಾತನಾಡಬಹುದು. ನಿಮ್ಮ ಮೂಲ ಧ್ವನಿ ಮುದ್ರಣ ನೇರವಾಗಿ ಅಧಿಕಾರಿಯನ್ನು ತಲುಪುತ್ತದೆ.",
    sos_speak_title: "🎤 ಮಾತನಾಡಿ",
    sos_speak_desc: "ಸ್ಥಿತಿಯನ್ನು ವಿವರಿಸುವ ಧ್ವನಿ ಸಂದೇಶವನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ. ಅಧಿಕಾರಿ ನಿಮ್ಮ ಧ್ವನಿಯನ್ನು ಕೇಳುತ್ತಾರೆ.",
    sos_no_voice_title: "➡️ ಧ್ವನಿಯಿಲ್ಲದೆ ಮುಂದುವರಿಯಿರಿ",
    sos_no_voice_desc: "ಧ್ವನಿ ರೆಕಾರ್ಡ್ ಮಾಡದೆಯೇ ತಕ್ಷಣ ನಿಮ್ಮ ಜಿಪಿಎಸ್ ಸ್ಥಳ ಮತ್ತು ವಿವರಗಳನ್ನು ಕಳುಹಿಸಿ.",
    sos_tell_happened: "🎤 ಏನು ಸಂಭವಿಸಿದೆ ಎಂದು ತಿಳಿಸಿ",
    sos_tell_happened_desc: "ಪ್ರಾಣಿಯಿರುವ ಸ್ಥಳ, ಬೆಳೆ ಹಾನಿ ಅಥವಾ ಅಪಾಯವನ್ನು ವಿವರಿಸಿ. ಸ್ಪಷ್ಟವಾಗಿ ಮಾತನಾಡಿ.",
    sos_tap_record: "ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ಮೈಕ್ ಒತ್ತಿರಿ",
    sos_recording_stop: "● ರೆಕಾರ್ಡ್ ಆಗುತ್ತಿದೆ... ನಿಲ್ಲಿಸಲು ಚೌಕವನ್ನು ಒತ್ತಿರಿ",
    sos_rec_captured: "✓ ಧ್ವನಿ ರೆಕಾರ್ಡ್ ಆಗಿದೆ",
    sos_listen_voice: "ಧ್ವನಿಯನ್ನು ಆಲಿಸಿ",
    sos_pause_playback: "ವಿರಾಮಗೊಳಿಸಿ",
    sos_rerecord: "ಮತ್ತೆ ರೆಕಾರ್ಡ್ ಮಾಡಿ",
    sos_voice_guarantee: "💡 ಈ ಮೂಲ ಧ್ವನಿ ಸಂದೇಶವು ನೇರವಾಗಿ ಅರಣ್ಯ ಕರ್ತವ್ಯ ಅಧಿಕಾರಿಗೆ ತಲುಪುತ್ತದೆ.",
    sos_send_with_voice: "ಧ್ವನಿ ಸಂದೇಶದೊಂದಿಗೆ SOS ಕಳುಹಿಸಿ ➔",
    sos_assessment_title: "ತ್ವರಿತ ಪರಿಸ್ಥಿತಿ ಮೌಲ್ಯಮಾಪನ",
    sos_assessment_desc: "ರಕ್ಷಣಾ ತಂಡಕ್ಕೆ ಆದ್ಯತೆ ನೀಡಲು ಸಹಾಯವಾಗುವಂತೆ ಉತ್ತರಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ:",
    sos_danger_immediate: "⚠️ ಮಾನವ ಜೀವಕ್ಕೆ ತಕ್ಷಣದ ಅಪಾಯವಿದೆ",
    sos_danger_immediate_sub: "ಜನರು ಅಥವಾ ಮಕ್ಕಳು ಅಪಾಯದಲ್ಲಿದ್ದಾರೆ",
    sos_animal_present: "ಪ್ರಾಣಿಯು ಪ್ರಸ್ತುತ ತೋಟದಲ್ಲೇ ಇದೆ",
    sos_animal_present_sub: "ಹೊಲದಲ್ಲಿ ಅಥವಾ ಬೇಲಿಯ ಬಳಿ ಈಗ ಕಾಣಿಸುತ್ತಿದೆ",
    sos_damage_ongoing: "ಬೆಳೆ ಅಥವಾ ಆಸ್ತಿಗೆ ಹಾನಿಯಾಗಿದೆ",
    sos_damage_ongoing_sub: "ಕಬ್ಬು, ಬಾಳೆ, ಟೊಮೆಟೊ ಅಥವಾ ಹನಿ ನೀರಾವರಿ ಪೈಪ್‌ಗಳು ಹಾನಿ",
    sos_send_now: "ಈಗಲೇ SOS ಕಳುಹಿಸಿ ➔",
    sos_sent_success: "SOS ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ!",
    sos_incident_ref: "ತುರ್ತು ಉಲ್ಲೇಖ ಸಂಖ್ಯೆ:",
    sos_type_col: "ಘಟನೆಯ ಪ್ರಕಾರ",
    sos_gps_col: "ಜಿಪಿಎಸ್ ಸ್ಥಳ",
    sos_voice_col: "ಧ್ವನಿ ಸಂದೇಶ",
    sos_status_col: "ಸ್ಥಿತಿ",
    sos_transmitted: "✓ ಕಳುಹಿಸಲಾಗಿದೆ",
    sos_delivered: "✓ ತಲುಪಿದೆ",
    sos_no_voice: "ಧ್ವನಿ ಇಲ್ಲ",
    sos_realtime_status: "🚨 ಲೈವ್ ರವಾನೆ ಸ್ಥಿತಿ",
    sos_safety_instructions: "🛡️ ತಕ್ಷಣದ ಸುರಕ್ಷತಾ ಸೂಚನೆಗಳು:",
    sos_call_authority_btn: "ಅಧಿಕಾರಿಗೆ ಕರೆ ಮಾಡಿ",
    sos_done_close: "ಮುಗಿದಿದೆ & ಮುಚ್ಚಿ",
    sos_safety_elephant: "ಆನೆಗಳಿಂದ ಕನಿಷ್ಠ 150 ಮೀಟರ್ ಸುರಕ್ಷಿತ ಅಂತರ ಕಾಯ್ದುಕೊಳ್ಳಿ. ಅವುಗಳ ಕಣ್ಣುಗಳ ಮೇಲೆ ನೇರವಾಗಿ ಬೆಳಕು ಚೆಲ್ಲಬೇಡಿ. ತೋಟದ ದೀಪಗಳನ್ನು ಆನ್ ಮಾಡಿ ಸುರಕ್ಷಿತ ಕಟ್ಟಡದಲ್ಲಿ ಆಶ್ರಯ ಪಡೆಯಿರಿ.",
    sos_safety_boar: "ಕಾಡುಹಂದಿಗಳನ್ನು ಬೆನ್ನಟ್ಟಬೇಡಿ; ಮರಿಗಳಿರುವ ಹಂದಿಗಳು ಆಕ್ರಮಣಕಾರಿಯಾಗಿ ದಾಳಿ ಮಾಡಬಹುದು. ದಟ್ಟವಾದ ಕಬ್ಬಿನ ಗದ್ದೆಗಳಿಗೆ ಒಬ್ಬರೇ ಹೋಗಬೇಡಿ.",
    sos_safety_leopard: "ತಕ್ಷಣದ ಅಪಾಯ: ಮಕ್ಕಳು ಮತ್ತು ಜಾನುವಾರುಗಳನ್ನು ಸುರಕ್ಷಿತ ಸ್ಥಳಕ್ಕೆ ಸ್ಥಳಾಂತರಿಸಿ. ಕೊಟ್ಟಿಗೆಯನ್ನು ಮುಚ್ಚಿ ಮನೆಯಲ್ಲೇ ಇರಿ.",
    sos_safety_bear: "ಕರಡಿ ಕಂಡರೆ ಓಡಬೇಡಿ. ಬೆನ್ನು ತೋರಿಸದೆ ನಿಧಾನವಾಗಿ ಹಿಂದೆ ಸರಿಯಿರಿ. ಶಾಂತವಾಗಿ ಮಾತನಾಡಿ ಅದು ದೂರ ಹೋಗಲು ಬಿಡಿ.",
    sos_safety_snake: "ಹಾವನ್ನು ಹಿಡಿಯಲು ಅಥವಾ ಕೊಲ್ಲಲು ಪ್ರಯತ್ನಿಸಬೇಡಿ. ಕಚ್ಚಿದರೆ ತಕ್ಷಣ ಆಸ್ಪತ್ರೆಗೆ ತೆರಳಿ.",
    sos_safety_fire: "ಹೊಗೆ ಬರುವ ದಿಕ್ಕಿನಿಂದ ದೂರ ಸರಿಯಿರಿ. ಮುಖ್ಯ ವಿದ್ಯುತ್ ಸ್ವಿಚ್ ಆಫ್ ಮಾಡಿ ಸುರಕ್ಷಿತವಾಗಿರಿ.",
    sos_safety_default: "ಅಪಾಯದಿಂದ ಸುರಕ್ಷಿತ ಅಂತರವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ. ವನ್ಯಜೀವಿಗಳನ್ನು ಪ್ರಚೋದಿಸಬೇಡಿ ಮತ್ತು ಸರ್ಕಾರಿ ಸಹಾಯಕ್ಕಾಗಿ ಕಾಯಿರಿ.",

    // Crops & Soils
    "Paddy": "ಭತ್ತ",
    "Tomato": "ಟೊಮೆಟೊ",
    "Groundnut": "ಕಡಲೆಕಾಯಿ",
    "Sugarcane": "ಕಬ್ಬು",
    "Cotton": "ಹತ್ತಿ",
    "Banana": "ಬಾಳೆಹಣ್ಣು",
    "Maize": "ಮೆಕ್ಕೆಜೋಳ",
    "Turmeric": "ಅರಿಶಿನ",
    "Red Loam": "ಕೆಂಪು ಮಣ್ಣು",
    "Clayey Alluvial": "ಜೇಡಿಮಣ್ಣಿನ ಮೆಕ್ಕಲು ಮಣ್ಣು",
    "Black Cotton Soil (Regur)": "ಕಪ್ಪು ಹತ್ತಿ ಮಣ್ಣು",
    "Sandy Loam": "ಮರಳು ಮಣ್ಣು",
    "Laterite Soil": "ಜಂಬಿಟ್ಟಿಗೆ ಮಣ್ಣು"
  },
  ml: {
    home: "ഹോം",
    nearby_equipment: "സമീപത്തെ ഉപകരണങ്ങൾ",
    list_equipment: "നിങ്ങളുടെ ഉപകരണങ്ങൾ ലിസ്റ്റ് ചെയ്യുക",
    nearby_storage: "സമീപത്തെ സംഭരണശാലകൾ & കോൾഡ് സ്റ്റോറേജ്",
    list_storage: "സംഭരണ സൗകര്യം രജിസ്റ്റർ ചെയ്യുക",
    shared_transport: "ഷെയർഡ് ട്രാൻസ്പോർട്ട്",
    weather: "കാലാവസ്ഥ",
    community: "കമ്മ്യൂണിറ്റി",
    market: "മാർക്കറ്റ്",
    expert_qa: "വിദഗ്ദ്ധ ചോദ്യോത്തരം",
    notifications: "അറിയിപ്പുകൾ",
    profile: "പ്രൊഫൈൽ",
    good_morning: "സുപ്രഭാതം",
    your_farm_dashboard: "നിങ്ങളുടെ ഫാം ഡാഷ്ബോർഡ്",
    weather_overview: "കാലാവസ്ഥാ അവലോകനം",
    current_conditions: "നിലവിലെ അവസ്ഥ",
    actionable_advisories: "ഉപദേശങ്ങൾ",
    seven_day_forecast: "7 ദിവസത്തെ പ്രവചനം",
    login_to_farmogram: "ലോഗിൻ ചെയ്യുക",
    mobile_number: "മൊബൈൽ നമ്പർ",
    password: "പാസ്‌വേഡ്",
    register_your_farm: "നിങ്ങളുടെ ഫാം രജിസ്റ്റർ ചെയ്യുക",
    farmer_onboarding: "കർഷക രജിസ്ട്രേഷൻ",
    full_name: "കർഷകന്റെ മുഴുവൻ പേര്",
    next: "അടുത്തത്",
    back: "പിന്നിലേക്ക്",
    create_password: "പാസ്‌വേഡ് സൃഷ്ടിക്കുക",
    confirm_password: "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
    select_language: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    state: "സംസ്ഥാനം",
    district: "ജില്ല",
    land_acres: "കൃഷിഭൂമി (ഏക്കർ)",
    soil_type: "മണ്ണിന്റെ തരം",
    primary_crops: "പ്രധാന വിളകൾ",
    create_profile: "പ്രൊഫൈൽ സൃഷ്ടിക്കുക",
    select_state: "സംസ്ഥാനം തിരഞ്ഞെടുക്കുക",
    select_district: "ജില്ല തിരഞ്ഞെടുക്കുക",
    select_soil: "മണ്ണിന്റെ തരം തിരഞ്ഞെടുക്കുക",
    search: "തിരയുക...",
    recommended_for_you: "നിങ്ങൾക്കായി ശുപാർശ ചെയ്യുന്നത്",
    market_prices: "മാർക്കറ്റ് വിലകൾ",
    disease_detection: "രോഗനിർണ്ണയം",
    irrigation: "ജലസേചനം",
    settings: "ക്രമീകരണങ്ങൾ",
    admin_view: "അഡ്മിൻ കാഴ്ച",
    farmer_view: "കർഷക കാഴ്ച",
    profit: "ലാഭം",
    schemes: "പദ്ധതികൾ",
    qa: "ചോദ്യോത്തരങ്ങൾ",
    smart_agri_decision: "സ്മാർട്ട് അഗ്രി തീരുമാനം & കമ്മ്യൂണിറ്റി",
    main_navigation: "പ്രധാന നാവിഗേഷൻ",
    management: "മാനേജ്മെന്റ്",
    settings_subtitle: "മുൻഗണനകൾ കൈകാര്യം ചെയ്യുക",
    language_region: "ഭാഷയും പ്രദേശവും",
    app_language: "ആപ്പ് ഭാഷ",
    select_pref_lang: "ഇഷ്ടപ്പെട്ട ഭാഷ തിരഞ്ഞെടുക്കുക",
    push_notifications: "അറിയിപ്പുകൾ",
    receive_alerts: "കാലാവസ്ഥാ അലർട്ടുകൾ സ്വീകരിക്കുക",
    accessibility: "ആക്സസിബിലിറ്റി",
    high_contrast: "ഉയർന്ന കോൺട്രാസ്റ്റ് മോഡ്",
    increase_contrast: "വായിക്കാൻ എളുപ്പമാക്കുക",
    about_farmogram: "ഫാർമോഗ്രാമിനെക്കുറിച്ച്",
    version_info: "പതിപ്പ് 1.0.0 (SIH 2026 പ്രോട്ടോടൈപ്പ്)"
,

    location: "സ്ഥലം:",
    temperature: "താപനില:",
    primary_soil: "പ്രധാന മണ്ണ്:",
    active_crops_in_season: "സീസണിലെ പ്രധാന വിളകൾ",
    agricultural_advisory: "കാർഷിക ഉപദേശം:",
    high_priority: "ഉയർന്ന മുൻഗണന",
    view_weather_advisory: "കാലാവസ്ഥാ ഉപദേശം കാണുക",
    decision_support_tools: "തീരുമാന പിന്തുണാ ഉപകരണങ്ങൾ",
    pre_sowing_intelligence: "വിത്ത് പാകുന്നത് മുതൽ വിളവെടുപ്പ് വരെയുള്ള വിവരങ്ങൾ",
    crop_advisor_desc: "AI അടിസ്ഥാനമാക്കിയുള്ള കാർഷിക ഉപദേശം",
    high_precision: "ഉയർന്ന കൃത്യത",
    weather_advisory: "കാലാവസ്ഥാ ഉപദേശം",
    weather_advisory_desc: "7-ദിവസത്തെ കാലാവസ്ഥാ പ്രവചനം",
    rain_alert: "മഴ അലർട്ട്",
    disease_desc: "രോഗപരിഹാരങ്ങൾക്കായി ഇലകൾ സ്കാൻ ചെയ്യുക",
    instant_ai: "തൽക്ഷണ AI",
    irrigation_desc: "കാലാവസ്ഥയും വളർച്ചാ ഘട്ടവും അനുസരിച്ചുള്ള ജലസേചനം",
    water_saving: "ജല സംരക്ഷണം",
    market_prices_desc: "തത്സമയ മാർക്കറ്റ് വിലകൾ",
    tomato_up: "തക്കാളി ↑ 8%",
    profit_calculator: "ലാഭ കാൽക്കുലേറ്റർ",
    profit_desc: "ചെലവുകൾ, വിളവ്, ROI എന്നിവ കണക്കാക്കുക",
    financials: "സാമ്പത്തികം",
    open_tool: "ടൂൾ തുറക്കുക",
    community_hub_title: "🌾 ഫാർമോഗ്രാം കമ്മ്യൂണിറ്റി & നോളഡ്ജ് ഹബ്",
    community_hub_subtitle: "ഇന്ത്യൻ കർഷകരുടെ അനുഭവങ്ങളും പരിശോധിച്ച ഉപദേശങ്ങളും",
    share_experience: "നിങ്ങളുടെ അനുഭവം പങ്കിടുക",
    // Tools & Actions
    crop_advisor: "വിള ഉപദേശകൻ",
    transport_pooling: "ഷെയർ ചെയ്ത ചരക്ക് ഗതാഗതം",
    transport_pooling_desc: "മാർക്കറ്റിലേക്ക് പോകുന്ന അടുത്തുള്ള കർഷകരുമായി വാഹനം പങ്കിടുകയും ചെലവ് കുറയ്ക്കുകയും ചെയ്യുക.",
    save_money: "₹800+ ലാഭിക്കാം",
    connect_agronomist: "കാർഷിക ഉദ്യോഗസ്ഥനുമായി ബന്ധപ്പെടുക",
    ready_scan: "രോഗനിർണ്ണയത്തിന് തയ്യാറാണ്",
    ready_scan_desc: "'വിള രോഗം പരിശോധിക്കുക' ക്ലിക്ക് ചെയ്ത് പൂർണ്ണ ലക്ഷണങ്ങളും ജൈവ, രാസ പ്രതിവിധികളും കാണുക.",
    upload_leaf_photo: "ബാധിച്ച ഇലയുടെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
    upload_leaf_sub: "പാടുകളോ നിറവ്യത്യാസമോ ഉള്ള ഇലകളുടെ അടുത്ത ഫോട്ടോ എടുക്കുക.",
    drag_drop_leaf: "ഇല ചിത്രം അപ്‌ലോഡ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക",
    png_jpg_max: "PNG, JPG, JPEG പരമാവധി 10MB",
    replace_image: "ചിത്രം മാറ്റുക",
    scanning_morphology: "ഇലയുടെ ഘടന സ്കാൻ ചെയ്യുന്നു...",
    analyzing_engine: "AI എൻജിൻ പരിശോധിക്കുന്നു...",
    analyze_crop_disease: "വിള രോഗം പരിശോധിക്കുക",
    detected_crop: "കണ്ടെത്തിയ വിള",
    observed_symptoms: "കണ്ടെത്തിയ രോഗലക്ഷണങ്ങൾ",
    ai_analysis_report: "വിശദമായ AI പരിശോധനാ റിപ്പോർട്ട്",
    preventive_measures: "പ്രതിരോധ നടപടികൾ",
    treatment_protocol: "ശുപാർശ ചെയ്ത ചികിത്സാരീതികൾ",
    step_label: "ഘട്ടം",
    confidence: "കൃത്യത",

    // Smart SOS & Wildlife Incident Reporting
    sos_banner_badge: "അടിയന്തര വന്യജീവി & കാർഷിക രക്ഷാ ദൗത്യം",
    sos_banner_title: "24/7 സ്മാർട്ട് SOS & അടിയന്തര റിപ്പോർട്ടിംഗ്",
    sos_banner_desc: "കാട്ടാന ആക്രമണം, കാട്ടുപന്നി ശല്യം, പുലി/കടുവ സാന്നിധ്യം, പാമ്പുകടി അല്ലെങ്കിൽ വിളനാശമോ? ജിപിഎസ് ലൊക്കേഷനും ശബ്ദ സന്ദേശവും സഹിതം വനംവകുപ്പിനെയും ദ്രുതകർമ്മ സേനയെയും ഉടൻ അറിയിക്കുക.",
    sos_launch_report: "അടിയന്തര സന്ദേശം അയക്കുക (SOS)",
    sos_modal_title: "സ്മാർട്ട് SOS & അടിയന്തര രക്ഷാദൗത്യം",
    sos_modal_sub: "വന്യജീവി സംഘർഷവും സർക്കാർ അധികാരികളിലേക്കുള്ള നേരിട്ടുള്ള ജിപിഎസ് റൂട്ടിംഗും",
    sos_step1_title: "ഏതുതരം അടിയന്തര സഹായമാണ് നിങ്ങൾക്ക് ആവശ്യം?",
    sos_step1_desc: "ഏറ്റവും അടുത്തുള്ള ഫോറസ്റ്റ് റേഞ്ച് അല്ലെങ്കിൽ റെസ്ക്യൂ ടീമിനെ അറിയിക്കാൻ മൃഗത്തെയോ അടിയന്തര വിഭാഗത്തെയോ തിരഞ്ഞെടുക്കുക.",
    sos_elephant_name: "കാട്ടാന",
    sos_elephant_tag: "തോട്ടത്തിന് സമീപം ആന / വിളനാശം / ജീവന് ഭീഷണി",
    sos_wild_boar_name: "കാട്ടുപന്നി",
    sos_wild_boar_tag: "കൃഷിയിടത്തിന് സമീപം കാട്ടുപന്നി / വിള നശിപ്പിക്കൽ",
    sos_monkey_name: "കുരങ്ങൻ കൂട്ടം",
    sos_monkey_tag: "കുരങ്ങുകളുടെ വിളയാട്ടം / പഴത്തോട്ട നാശം",
    sos_leopard_name: "പുലി / കടുവ",
    sos_leopard_tag: "അപകടകാരിയായ വന്യമൃഗം / ജീവന് ഭീഷണി",
    sos_bear_name: "കരടി",
    sos_bear_tag: "കരടിയുടെ സാന്നിധ്യം / തോട്ടത്തിൽ കടന്നുകയറൽ",
    sos_snake_name: "വിഷപ്പാമ്പ്",
    sos_snake_tag: "വിഷപ്പാമ്പ് ഭീഷണി / കടിയേൽക്കാനുള്ള സാധ്യത",
    sos_other_wildlife_name: "മറ്റ് വന്യജീവികൾ",
    sos_other_wildlife_tag: "മാൻ, കാട്ടുപോത്ത് അല്ലെങ്കിൽ മറ്റ് കാട്ടുമൃഗങ്ങൾ",
    sos_other_sos_name: "മറ്റ് അടിയന്തരാവസ്ഥകൾ",
    sos_other_sos_tag: "തീപിടുത്തം, വൈദ്യസഹായം, മോഷണം, ദുരന്തം",
    sos_back_animal: "മൃഗങ്ങളുടെ തിരഞ്ഞെടുപ്പിലേക്ക് മടങ്ങുക",
    sos_select_other_title: "മറ്റ് അടിയന്തര വിഭാഗം തിരഞ്ഞെടുക്കുക",
    sos_select_other_desc: "ഈ റിപ്പോർട്ട് പ്രാദേശിക ഫയർഫോഴ്സ്, പോലീസ് അല്ലെങ്കിൽ വെറ്ററിനറി വകുപ്പിലേക്ക് കൈമാറും.",
    sos_other_fire: "തീപിടുത്തം",
    sos_other_fire_desc: "വിളകൾക്ക് തീപിടുത്തം, വൈക്കോൽക്കൂന അല്ലെങ്കിൽ തൊഴുത്തിന് തീപിടുത്തം",
    sos_other_flood: "വെള്ളപ്പൊക്കം / വെള്ളം കയറൽ",
    sos_other_flood_desc: "കനാൽ പൊട്ടൽ അല്ലെങ്കിൽ കൃഷിയിടത്തിൽ വെള്ളം കയറൽ",
    sos_other_theft: "മോഷണം / സുരക്ഷ",
    sos_other_theft_desc: "അതിക്രമിച്ചു കടക്കൽ അല്ലെങ്കിൽ കാർഷിക വിള മോഷണം",
    sos_other_livestock: "കന്നുകാലി അടിയന്തരാവസ്ഥ",
    sos_other_livestock_desc: "പരിക്കേറ്റ കന്നുകാലികൾ, പേവിഷബാധ ഭീഷണി",
    sos_other_human: "മനുഷ്യജീവന് ഭീഷണി",
    sos_other_human_desc: "തൊഴിലാളിക്ക് പരിക്ക് അല്ലെങ്കിൽ അപകടത്തിൽപ്പെടൽ",
    sos_other_storm: "കൊടുങ്കാറ്റ് / മരം വീഴൽ",
    sos_other_storm_desc: "വൈദ്യുതി ലൈൻ പൊട്ടിവീഴൽ അല്ലെങ്കിൽ കാറ്റുമൂലമുള്ള നാശനഷ്ടം",
    sos_incident_detected: "സംഭവം രേഖപ്പെടുത്തി",
    sos_step_verifying: "ഘട്ടം 1/3: ജിപിഎസും അധികാരപരിധിയും സ്ഥിരീകരിക്കുന്നു",
    sos_live_gps: "📍 നിങ്ങളുടെ തത്സമയ ജിപിഎസ് ലൊക്കേഷൻ",
    sos_jurisdiction: "🏛️ ഫോറസ്റ്റ് ഡിവിഷൻ: സത്യമംഗലം / ഈറോഡ് റേഞ്ച്",
    sos_resp_authority: "ഉത്തരവാദപ്പെട്ട സർക്കാർ അധികാരി",
    sos_authority_desc: "തമിഴ്നാട് ഫോറസ്റ്റ് ഡിപ്പാർട്ട്മെന്റ് • ടോൾ-ഫ്രീ വന്യജീവി ഹെൽപ്പ്‌ലൈൻ: 1800-425-4545 / 1926",
    sos_change_type: "വിഭാഗം മാറ്റുക",
    sos_confirm_location: "സ്ഥലം സ്ഥിരീകരിച്ച് മുന്നോട്ട് പോകുക ➔",
    sos_voice_choice_title: "എന്താണ് സംഭവിച്ചതെന്ന് ശബ്ദത്തിലൂടെ ഉദ്യോഗസ്ഥനോട് പറയാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?",
    sos_voice_choice_desc: "നിങ്ങളുടെ സ്വന്തം ഭാഷയിൽ സംസാരിക്കാം. നിങ്ങളുടെ യഥാർത്ഥ ശബ്ദ റെക്കോർഡിംഗ് ഉദ്യോഗസ്ഥന് നേരിട്ട് ലഭിക്കും.",
    sos_speak_title: "🎤 സംസാരിക്കുക",
    sos_speak_desc: "സാഹചര്യം വിവരിക്കുന്ന ശബ്ദ സന്ദേശം റെക്കോർഡ് ചെയ്യുക. ഉദ്യോഗസ്ഥൻ നിങ്ങളുടെ ശബ്ദം കേൾക്കും.",
    sos_no_voice_title: "➡️ ശബ്ദമില്ലാതെ തുടരുക",
    sos_no_voice_desc: "ശബ്ദം റെക്കോർഡ് ചെയ്യാതെ ജിപിഎസ് ലൊക്കേഷനും വിവരങ്ങളും ഉടൻ അയക്കുക.",
    sos_tell_happened: "🎤 എന്താണ് സംഭവിച്ചതെന്ന് പറയുക",
    sos_tell_happened_desc: "മൃഗത്തിന്റെ സ്ഥാനം, വിളനാശം അല്ലെങ്കിൽ അപകടം വിവരിക്കുക. സ്വന്തം ഭാഷയിൽ സംസാരിക്കുക.",
    sos_tap_record: "റെക്കോർഡിംഗ് ആരംഭിക്കാൻ മൈക്ക് അമർത്തുക",
    sos_recording_stop: "● റെക്കോർഡ് ചെയ്യുന്നു... നിർത്താൻ സമചതുരം അമർത്തുക",
    sos_rec_captured: "✓ ശബ്ദ സന്ദേശം റെക്കോർഡ് ചെയ്തു",
    sos_listen_voice: "ശബ്ദം കേൾക്കുക",
    sos_pause_playback: "താൽക്കാലികമായി നിർത്തുക",
    sos_rerecord: "വീണ്ടും റെക്കോർഡ് ചെയ്യുക",
    sos_voice_guarantee: "💡 ഈ യഥാർത്ഥ ശബ്ദ സന്ദേശം ഫോറസ്റ്റ് ഡ്യൂട്ടി ഓഫീസർക്ക് നേരിട്ട് ലഭ്യമാക്കും.",
    sos_send_with_voice: "ശബ്ദ സന്ദേശത്തോടൊപ്പം SOS അയക്കുക ➔",
    sos_assessment_title: "പെട്ടെന്നുള്ള സ്ഥിതിഗതികൾ വിലയിരുത്തൽ",
    sos_assessment_desc: "രക്ഷാപ്രവർത്തകർക്ക് മുൻഗണന നൽകാൻ സഹായിക്കുന്ന ഉത്തരങ്ങൾ തിരഞ്ഞെടുക്കുക:",
    sos_danger_immediate: "⚠️ മനുഷ്യജീവന് പെട്ടെന്നുള്ള അപകടസാധ്യതയുണ്ട്",
    sos_danger_immediate_sub: "ആളുകളോ കുട്ടികളോ സമീപത്തുണ്ട്, ഭീഷണിയിലാണ്",
    sos_animal_present: "മൃഗം നിലവിൽ കൃഷിയിടത്തിലുണ്ട്",
    sos_animal_present_sub: "പാടത്തോ അതിർത്തിയിലോ ഇപ്പോൾ കാണാം",
    sos_damage_ongoing: "വിളകൾക്കോ സ്വത്തിനോ നാശനഷ്ടം സംഭവിച്ചു",
    sos_damage_ongoing_sub: "കരിമ്പ്, വാഴ, തക്കാളി അല്ലെങ്കിൽ ഡ്രിപ്പ് പൈപ്പുകൾ നശിച്ചു",
    sos_send_now: "ഇപ്പോൾ തന്നെ SOS അയക്കുക ➔",
    sos_sent_success: "SOS വിജയകരമായി അയച്ചു!",
    sos_incident_ref: "അടിയന്തര റഫറൻസ് നമ്പർ:",
    sos_type_col: "സംഭവത്തിന്റെ തരം",
    sos_gps_col: "ജിപിഎസ് ലൊക്കേഷൻ",
    sos_voice_col: "ശബ്ദ സന്ദേശം",
    sos_status_col: "നിലവിലെ അവസ്ഥ",
    sos_transmitted: "✓ കൈമാറി",
    sos_delivered: "✓ എത്തിച്ചു",
    sos_no_voice: "ശബ്ദമില്ല",
    sos_realtime_status: "🚨 തത്സമയ നടപടിക്രമങ്ങൾ",
    sos_safety_instructions: "🛡️ അടിയന്തര സുരക്ഷാ നിർദ്ദേശങ്ങൾ:",
    sos_call_authority_btn: "ഉദ്യോഗസ്ഥനെ വിളിക്കുക",
    sos_done_close: "പൂർത്തിയായി & അടയ്ക്കുക",
    sos_safety_elephant: "ആനകളിൽ നിന്ന് കുറഞ്ഞത് 150 മീറ്റർ സുരക്ഷിതമായ അകലം പാലിക്കുക. അവയുടെ കണ്ണിലേക്ക് നേരിട്ട് ടോർച്ച് അടിക്കരുത്. ലൈറ്റുകൾ ഓണാക്കി സുരക്ഷിതമായ കെട്ടിടത്തിൽ കഴിയുക.",
    sos_safety_boar: "കാട്ടുപന്നികളെ വളയാനോ തുരത്താനോ ശ്രമിക്കരുത്; കുഞ്ഞുങ്ങളുള്ള പന്നികൾ ആക്രമിക്കാൻ സാധ്യതയുണ്ട്. കരിമ്പിൻ തോട്ടങ്ങളിലേക്ക് ഒറ്റയ്ക്ക് പോകരുത്.",
    sos_safety_leopard: "അടിയന്തര ഭീഷണി: കുട്ടികളെയും കന്നുകാലികളെയും ഉടൻ സുരക്ഷിത സ്ഥാനത്തേക്ക് മാറ്റുക. തൊഴുത്തുകൾ പൂട്ടി വീടിനുള്ളിൽ കഴിയുക.",
    sos_safety_bear: "കരടിയെ കണ്ടാൽ ഓടരുത്. പുറം തിരിയാതെ പതുക്കെ പിന്നോട്ട് മാറുക. ശബ്ദം ഉണ്ടാക്കി അത് ഒഴിഞ്ഞുപോകാൻ അനുവദിക്കുക.",
    sos_safety_snake: "പാമ്പിനെ പിടിക്കാനോ കൊല്ലാനോ ശ്രമിക്കരുത്. കടിയേറ്റാൽ കടിയേറ്റ ഭാഗം അനക്കാതെ വെച്ച് ഉടൻ ആശുപത്രിയിലെത്തുക.",
    sos_safety_fire: "പുക വരുന്ന ദിശയിൽ നിന്ന് മാറുക. പ്രധാന വൈദ്യുതി സ്വിച്ച് ഓഫ് ചെയ്യുക.",
    sos_safety_default: "അപകടത്തിൽ നിന്ന് സുരക്ഷിതമായ അകലം പാലിക്കുക. വന്യജീവികളെ പ്രകോപിപ്പിക്കരുത്, സർക്കാർ സഹായത്തിനായി കാത്തിരിക്കുക.",

    // Crops & Soils
    "Paddy": "നെല്ല്",
    "Tomato": "തക്കാളി",
    "Groundnut": "നിലക്കടല",
    "Sugarcane": "കരിമ്പ്",
    "Cotton": "പരുത്തി",
    "Banana": "വാഴ",
    "Maize": "ചോളം",
    "Turmeric": "മഞ്ഞൾ",
    "Red Loam": "ചുവന്ന മണ്ണ്",
    "Clayey Alluvial": "എക്കൽ മണ്ണ്",
    "Black Cotton Soil (Regur)": "കരിമണ്ണ്",
    "Sandy Loam": "മണൽ മണ്ണ്",
    "Laterite Soil": "ചെങ്കൽ മണ്ണ്"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('farmogram_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('farmogram_lang', currentLang);
  }, [currentLang]);

  const t = (key) => {
    if (!translations[currentLang]) return key;
    if (!translations[currentLang][key]) {
      // Fallback to English if translation is missing
      return translations['en'][key] || key;
    }
    return translations[currentLang][key];
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setCurrentLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
