import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    home: "Home",
    weather: "Weather",
    community: "Community",
    market: "Market",
    expert_qa: "Expert Q&A",
    notifications: "Notifications",
    profile: "Profile",
    good_morning: "Good Morning",
    your_farm_dashboard: "Your Farm Dashboard",
    weather_overview: "Weather Overview",
    current_conditions: "Current Conditions",
    actionable_advisories: "Actionable Advisories",
    seven_day_forecast: "7-Day Forecast",
    login_to_farmogram: "Login to Farmogram",
    mobile_number: "Mobile Number",
    password: "Password",
    register_your_farm: "Register Your Farm",
    farmer_onboarding: "Farmer Onboarding",
    full_name: "Farmer Full Name",
    next: "Next",
    back: "Back",
    create_password: "Create Password",
    confirm_password: "Confirm Password",
    select_language: "Select Your Language",
    state: "State",
    district: "District",
    land_acres: "Cultivable Land (Acres)",
    soil_type: "Dominant Soil Type",
    primary_crops: "Primary Crops Cultivated",
    create_profile: "Create Farmer Profile & Enter",
    select_state: "Select your State",
    select_district: "Select your District",
    select_soil: "Select Soil Type",
    search: "Search...",
    recommended_for_you: "Recommended For You",
    step_language: "Select Language",
    step_basic_info: "Basic Information",
    step_security: "Account Security",
    step_state: "Farm Location (State)",
    step_district: "District & Land Details",
    placeholder_name: "e.g., Ramasamy K.",
    placeholder_phone: "+91 94432 10987",
    mobile_verified: "Mobile number verified successfully. Create a password for your account.",
    already_registered: "Already registered?",
    login_here: "Login Here",
    market_prices: "Live Market Prices",
    disease_detection: "Disease Detection",
    irrigation: "Irrigation",
    settings: "Settings",
    admin_view: "Admin View",
    farmer_view: "Farmer View",
    profit: "Profit",
    schemes: "Schemes",
    qa: "Q&A",
    smart_agri_decision: "Smart Agri Decision & Community",
    main_navigation: "MAIN NAVIGATION",
    management: "MANAGEMENT",
    settings_subtitle: "Manage your preferences and app experience",
    language_region: "Language & Region",
    app_language: "App Language",
    select_pref_lang: "Select your preferred language for the application",
    push_notifications: "Push Notifications",
    receive_alerts: "Receive alerts for weather updates and advisories",
    accessibility: "Accessibility",
    high_contrast: "High Contrast Mode",
    increase_contrast: "Increase contrast for better readability",
    about_farmogram: "About Farmogram",
    version_info: "Version 1.0.0 (SIH 2026 Prototype)"
,

    location: "Location:",
    temperature: "Temperature:",
    primary_soil: "Primary Soil:",
    active_crops_in_season: "Active Crops in Season",
    agricultural_advisory: "Agricultural Advisory:",
    high_priority: "High Priority",
    view_weather_advisory: "View Weather Advisory",
    decision_support_tools: "Decision Support Tools",
    pre_sowing_intelligence: "Pre-sowing to post-harvest intelligence",
    crop_advisor_desc: "AI Multi-factor agronomic advice",
    high_precision: "High Precision",
    weather_advisory: "Weather Advisory",
    weather_advisory_desc: "7-day microclimate forecast",
    rain_alert: "Rain Alert",
    disease_desc: "Scan leaf lesions for remedies",
    instant_ai: "Instant AI",
    irrigation_desc: "Weather & stage-based schedule",
    water_saving: "Water Saving",
    market_prices_desc: "Live Mandi rates & trends",
    tomato_up: "Tomato ↑ 8%",
    profit_calculator: "Profit Calculator",
    profit_desc: "Calculate costs, yield & ROI",
    financials: "Financials",
    open_tool: "Open Tool",
    community_hub_title: "🌾 Farmogram Community & Knowledge Hub",
    community_hub_subtitle: "Real experiences, verified advice & agronomic practices from Indian farmers",
    share_experience: "Share Your Experience"
  },
  hi: {
    home: "होम",
    weather: "मौसम",
    community: "समुदाय",
    market: "बाज़ार",
    expert_qa: "विशेषज्ञ प्रश्नोत्तर",
    notifications: "सूचनाएं",
    profile: "प्रोफ़ाइल",
    good_morning: "सुप्रभात",
    your_farm_dashboard: "आपका कृषि डैशबोर्ड",
    weather_overview: "मौसम अवलोकन",
    current_conditions: "वर्तमान स्थिति",
    actionable_advisories: "कार्रवाई योग्य सलाह",
    seven_day_forecast: "7-दिवसीय पूर्वानुमान",
    login_to_farmogram: "फार्मोग्राम में लॉगिन करें",
    mobile_number: "मोबाइल नंबर",
    password: "पासवर्ड",
    register_your_farm: "अपना खेत पंजीकृत करें",
    farmer_onboarding: "किसान पंजीकरण",
    full_name: "किसान का पूरा नाम",
    next: "अगला",
    back: "पीछे",
    create_password: "पासवर्ड बनाएं",
    confirm_password: "पासवर्ड की पुष्टि करें",
    select_language: "अपनी भाषा चुनें",
    state: "राज्य",
    district: "ज़िला",
    land_acres: "कृषि योग्य भूमि (एकड़)",
    soil_type: "प्रमुख मिट्टी का प्रकार",
    primary_crops: "मुख्य फसलें",
    create_profile: "किसान प्रोफाइल बनाएं और प्रवेश करें",
    select_state: "अपना राज्य चुनें",
    select_district: "अपना ज़िला चुनें",
    select_soil: "मिट्टी का प्रकार चुनें",
    search: "खोजें...",
    recommended_for_you: "आपके लिए अनुशंसित",
    market_prices: "लाइव बाजार मूल्य",
    disease_detection: "रोग पहचान",
    irrigation: "सिंचाई",
    settings: "सेटिंग्स",
    admin_view: "एडमिन व्यू",
    farmer_view: "किसान व्यू",
    profit: "मुनाफा",
    schemes: "योजनाएं",
    qa: "प्रश्नोत्तर",
    smart_agri_decision: "स्मार्ट कृषि निर्णय और समुदाय",
    main_navigation: "मुख्य नेविगेशन",
    management: "प्रबंधन",
    settings_subtitle: "अपनी प्राथमिकताएं प्रबंधित करें",
    language_region: "भाषा और क्षेत्र",
    app_language: "ऐप की भाषा",
    select_pref_lang: "अपनी पसंदीदा भाषा चुनें",
    push_notifications: "पुश सूचनाएँ",
    receive_alerts: "मौसम और सलाह के लिए अलर्ट प्राप्त करें",
    accessibility: "अभिगम्यता",
    high_contrast: "उच्च कंट्रास्ट मोड",
    increase_contrast: "बेहतर पठनीयता के लिए कंट्रास्ट बढ़ाएं",
    about_farmogram: "फार्मोग्राम के बारे में",
    version_info: "संस्करण 1.0.0 (SIH 2026 प्रोटोटाइप)"
,

    location: "स्थान:",
    temperature: "तापमान:",
    primary_soil: "प्राथमिक मिट्टी:",
    active_crops_in_season: "सीज़न में सक्रिय फसलें",
    agricultural_advisory: "कृषि सलाहकार:",
    high_priority: "उच्च प्राथमिकता",
    view_weather_advisory: "मौसम सलाहकार देखें",
    decision_support_tools: "निर्णय समर्थन उपकरण",
    pre_sowing_intelligence: "बुवाई से कटाई तक की जानकारी",
    crop_advisor_desc: "AI बहु-कारक कृषि सलाह",
    high_precision: "उच्च सटीकता",
    weather_advisory: "मौसम सलाहकार",
    weather_advisory_desc: "7-दिवसीय सूक्ष्म जलवायु पूर्वानुमान",
    rain_alert: "बारिश का अलर्ट",
    disease_desc: "उपाय के लिए पत्तियों के घाव स्कैन करें",
    instant_ai: "त्वरित AI",
    irrigation_desc: "मौसम और चरण-आधारित अनुसूची",
    water_saving: "जल बचत",
    market_prices_desc: "लाइव मंडी दरें और रुझान",
    tomato_up: "टमाटर ↑ 8%",
    profit_calculator: "मुनाफा कैलकुलेटर",
    profit_desc: "लागत, उपज और ROI की गणना करें",
    financials: "वित्तीय",
    open_tool: "उपकरण खोलें",
    community_hub_title: "🌾 फार्मोग्राम समुदाय और ज्ञान केंद्र",
    community_hub_subtitle: "भारतीय किसानों के वास्तविक अनुभव, सत्यापित सलाह और कृषि पद्धतियां",
    share_experience: "अपना अनुभव साझा करें"
  },
  ta: {
    home: "முகப்பு",
    weather: "வானிலை",
    community: "சமூகம்",
    market: "சந்தை",
    expert_qa: "நிபுணர் கேள்வி பதில்",
    notifications: "அறிவிப்புகள்",
    profile: "சுயவிவரம்",
    good_morning: "காலை வணக்கம்",
    your_farm_dashboard: "உங்கள் பண்ணை முகப்பு",
    weather_overview: "வானிலை கண்ணோட்டம்",
    current_conditions: "தற்போதைய நிலை",
    actionable_advisories: "செயல்படக்கூடிய ஆலோசனைகள்",
    seven_day_forecast: "7 நாள் கணிப்பு",
    login_to_farmogram: "உள்நுழைய",
    mobile_number: "மொபைல் எண்",
    password: "கடவுச்சொல்",
    register_your_farm: "பண்ணையை பதிவு செய்க",
    farmer_onboarding: "விவசாயி பதிவு",
    full_name: "விவசாயி முழு பெயர்",
    next: "அடுத்து",
    back: "பின்",
    create_password: "கடவுச்சொல் உருவாக்கு",
    confirm_password: "கடவுச்சொல்லை உறுதிப்படுத்து",
    select_language: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    state: "மாநிலம்",
    district: "மாவட்டம்",
    land_acres: "விவசாய நிலம் (ஏக்கர்)",
    soil_type: "மண் வகை",
    primary_crops: "முதன்மை பயிர்கள்",
    create_profile: "சுயவிவரத்தை உருவாக்கி உள்ளே நுழைக",
    select_state: "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
    select_district: "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்",
    select_soil: "மண் வகையைத் தேர்ந்தெடுக்கவும்",
    search: "தேடு...",
    recommended_for_you: "பரிந்துரைக்கப்படுபவை",
    step_language: "மொழியைத் தேர்ந்தெடுக்கவும்",
    step_basic_info: "அடிப்படை தகவல்",
    step_security: "கணக்கு பாதுகாப்பு",
    step_state: "பண்ணை இடம் (மாநிலம்)",
    step_district: "மாவட்டம் மற்றும் நில விவரங்கள்",
    placeholder_name: "உதா: ராமசாமி கி.",
    placeholder_phone: "+91 94432 10987",
    mobile_verified: "மொபைல் எண் சரிபார்க்கப்பட்டது. கடவுச்சொல்லை உருவாக்கவும்.",
    already_registered: "ஏற்கனவே பதிவு செய்துள்ளீர்களா?",
    login_here: "இங்கே உள்நுழையவும்",
    market_prices: "சந்தை விலைகள்",
    disease_detection: "நோய் கண்டறிதல்",
    irrigation: "நீர்ப்பாசனம்",
    settings: "அமைப்புகள்",
    admin_view: "நிர்வாகி பார்வை",
    farmer_view: "விவசாயி பார்வை",
    profit: "இலாபம்",
    schemes: "திட்டங்கள்",
    qa: "கேள்வி-பதில்",
    smart_agri_decision: "ஸ்மார்ட் வேளாண் முடிவு & சமூகம்",
    main_navigation: "முக்கிய வழிசெலுத்தல்",
    management: "மேலாண்மை",
    settings_subtitle: "உங்கள் விருப்பங்களை நிர்வகிக்கவும்",
    language_region: "மொழி & பகுதி",
    app_language: "பயன்பாட்டு மொழி",
    select_pref_lang: "விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    push_notifications: "அறிவிப்புகள்",
    receive_alerts: "வானிலை எச்சரிக்கைகளைப் பெறுக",
    accessibility: "அணுகல்",
    high_contrast: "உயர் மாறுபாடு பயன்முறை",
    increase_contrast: "வாசிப்புத்திறனை அதிகரிக்கவும்",
    about_farmogram: "பார்மோகிராம் பற்றி",
    version_info: "பதிப்பு 1.0.0 (SIH 2026 முன்மாதிரி)"
,

    location: "இடம்:",
    temperature: "வெப்பநிலை:",
    primary_soil: "முதன்மை மண்:",
    active_crops_in_season: "பருவத்தில் செயலில் உள்ள பயிர்கள்",
    agricultural_advisory: "வேளாண் ஆலோசனை:",
    high_priority: "அதிக முன்னுரிமை",
    view_weather_advisory: "வானிலை ஆலோசனையைக் காண்க",
    decision_support_tools: "முடிவு ஆதரவு கருவிகள்",
    pre_sowing_intelligence: "விதைப்பு முதல் அறுவடை வரை நுண்ணறிவு",
    crop_advisor_desc: "AI பல காரணி உழவியல் ஆலோசனை",
    high_precision: "உயர் துல்லியம்",
    weather_advisory: "வானிலை ஆலோசனை",
    weather_advisory_desc: "7-நாள் நுண்-கணிப்பு",
    rain_alert: "மழை எச்சரிக்கை",
    disease_desc: "தீர்வுகளுக்கு இலைப்புண்களை ஸ்கேன் செய்யுங்கள்",
    instant_ai: "உடனடி AI",
    irrigation_desc: "வானிலை & நிலை அடிப்படையிலான அட்டவணை",
    water_saving: "நீர் சேமிப்பு",
    market_prices_desc: "நேரலை மண்டி விலைகள்",
    tomato_up: "தக்காளி ↑ 8%",
    profit_calculator: "இலாப கணக்கீட்டான்",
    profit_desc: "செலவுகள், விளைச்சல் மற்றும் ROI",
    financials: "நிதியியல்",
    open_tool: "கருவியைத் திற",
    community_hub_title: "🌾 பார்மோகிராம் சமூகம் & அறிவு மையம்",
    community_hub_subtitle: "இந்திய விவசாயிகளின் உண்மையான அனுபவங்கள் & சரிபார்க்கப்பட்ட ஆலோசனைகள்",
    share_experience: "உங்கள் அனுபவத்தைப் பகிரவும்",
    
    // States
    "Andhra Pradesh": "ஆந்திரப் பிரதேசம்",
    "Arunachal Pradesh": "அருணாச்சல பிரதேசம்",
    "Assam": "அசாம்",
    "Bihar": "பீகார்",
    "Chandigarh (UT)": "சண்டிகர்",
    "Chhattisgarh": "சத்தீஸ்கர்",
    "Dadra and Nagar Haveli (UT)": "தாத்ரா மற்றும் நகர் ஹவேலி",
    "Daman and Diu (UT)": "டாமன் மற்றும் டையூ",
    "Delhi (NCT)": "டெல்லி",
    "Goa": "கோவா",
    "Gujarat": "குஜராத்",
    "Haryana": "ஹரியானா",
    "Himachal Pradesh": "இமாச்சல பிரதேசம்",
    "Jammu and Kashmir": "ஜம்மு காஷ்மீர்",
    "Jharkhand": "ஜார்க்கண்ட்",
    "Karnataka": "கர்நாடகா",
    "Kerala": "கேரளா",
    "Lakshadweep (UT)": "லட்சத்தீவு",
    "Madhya Pradesh": "மத்தியப் பிரதேசம்",
    "Maharashtra": "மகாராஷ்டிரா",
    "Manipur": "மணிப்பூர்",
    "Meghalaya": "மேகாலயா",
    "Mizoram": "மிசோரம்",
    "Nagaland": "நாகாலாந்து",
    "Odisha": "ஒடிசா",
    "Puducherry (UT)": "புதுச்சேரி",
    "Punjab": "பஞ்சாப்",
    "Rajasthan": "ராஜஸ்தான்",
    "Sikkim": "சிக்கிம்",
    "Tamil Nadu": "தமிழ்நாடு",
    "Telangana": "தெலுங்கானா",
    "Tripura": "திரிபுரா",
    "Uttar Pradesh": "உத்தரப் பிரதேசம்",
    "Uttarakhand": "உத்தரகாண்ட்",
    "West Bengal": "மேற்கு வங்காளம்",

    // Districts (Subset for testing)
    "Coimbatore": "கோயம்புத்தூர்",
    "Erode": "ஈரோடு",
    "Salem": "சேலம்",
    "Tiruppur": "திருப்பூர்",
    "Namakkal": "நாமக்கல்",

    // Soil Types
    "Red Loam": "செம்மண்",
    "Clayey Alluvial": "வண்டல் மண்",
    "Black Cotton Soil (Regur)": "கரிசல் மண்",
    "Sandy Loam": "மணற்பாங்கான மண்",
    "Laterite Soil": "செம்புரை மண்",

    // Crops
    "Paddy": "நெல்",
    "Tomato": "தக்காளி",
    "Groundnut": "நிலக்கடலை",
    "Sugarcane": "கரும்பு",
    "Cotton": "பருத்தி",
    "Banana": "வாழை",
    "Maize": "மக்காச்சோளம்",
    "Turmeric": "மஞ்சள்"
  },
  te: {
    home: "హోమ్",
    weather: "వాతావరణం",
    community: "కమ్యూనిటీ",
    market: "మార్కెట్",
    expert_qa: "నిపుణుల Q&A",
    notifications: "నోటిఫికేషన్లు",
    profile: "ప్రొఫైల్",
    good_morning: "శుభోదయం",
    your_farm_dashboard: "మీ ఫామ్ డాష్‌బోర్డ్",
    weather_overview: "వాతావరణ అవలోకనం",
    current_conditions: "ప్రస్తుత పరిస్థితులు",
    actionable_advisories: "చర్యలు",
    seven_day_forecast: "7 రోజుల సూచన",
    login_to_farmogram: "లాగిన్",
    mobile_number: "మొబైల్ నంబర్",
    password: "పాస్వర్డ్",
    register_your_farm: "మీ పొలాన్ని నమోదు చేసుకోండి",
    farmer_onboarding: "రైతు నమోదు",
    full_name: "రైతు పూర్తి పేరు",
    next: "తరువాత",
    back: "వెనుకకు",
    create_password: "పాస్వర్డ్ సృష్టించండి",
    confirm_password: "పాస్వర్డ్ నిర్ధారించండి",
    select_language: "భాషను ఎంచుకోండి",
    state: "రాష్ట్రం",
    district: "జిల్లా",
    land_acres: "సాగు భూమి (ఎకరాలు)",
    soil_type: "మట్టి రకం",
    primary_crops: "పండించే ప్రధాన పంటలు",
    create_profile: "ప్రొఫైల్ సృష్టించండి",
    select_state: "రాష్ట్రాన్ని ఎంచుకోండి",
    select_district: "జిల్లాను ఎంచుకోండి",
    select_soil: "మట్టి రకాన్ని ఎంచుకోండి",
    search: "శోధించండి...",
    recommended_for_you: "మీ కోసం సిఫార్సు చేయబడినవి",
    market_prices: "మార్కెట్ ధరలు",
    disease_detection: "వ్యాధి గుర్తింపు",
    irrigation: "నీటిపారుదల",
    settings: "సెట్టింగులు",
    admin_view: "అడ్మిన్ వీక్షణ",
    farmer_view: "రైతు వీక్షణ",
    profit: "లాభం",
    schemes: "పథకాలు",
    qa: "ప్రశ్నోత్తరాలు",
    smart_agri_decision: "స్మార్ట్ అగ్రి నిర్ణయం & సంఘం",
    main_navigation: "ప్రధాన నావిగేషన్",
    management: "నిర్వహణ",
    settings_subtitle: "ప్రాధాన్యతలను నిర్వహించండి",
    language_region: "భాష & ప్రాంతం",
    app_language: "యాప్ భాష",
    select_pref_lang: "ప్రాధాన్య భాషను ఎంచుకోండి",
    push_notifications: "నోటిఫికేషన్‌లు",
    receive_alerts: "వాతావరణ హెచ్చరికలను స్వీకరించండి",
    accessibility: "సౌలభ్యం",
    high_contrast: "అధిక కాంట్రాస్ట్ మోడ్",
    increase_contrast: "చదవడానికి సులభంగా ఉండేలా మార్చండి",
    about_farmogram: "ఫార్మోగ్రామ్ గురించి",
    version_info: "వెర్షన్ 1.0.0 (SIH 2026 ప్రోటోటైప్)"
,

    location: "స్థానం:",
    temperature: "ఉష్ణోగ్రత:",
    primary_soil: "ప్రాథమిక మట్టి:",
    active_crops_in_season: "సీజన్‌లో క్రియాశీల పంటలు",
    agricultural_advisory: "వ్యవసాయ సలహా:",
    high_priority: "అధిక ప్రాధాన్యత",
    view_weather_advisory: "వాతావరణ సలహాను చూడండి",
    decision_support_tools: "నిర్ణయ మద్దతు సాధనాలు",
    pre_sowing_intelligence: "విత్తనాల నుండి కోత వరకు మేధస్సు",
    crop_advisor_desc: "AI బహుళ-కారకాల వ్యవసాయ సలహా",
    high_precision: "అధిక ఖచ్చితత్వం",
    weather_advisory: "వాతావరణ సలహా",
    weather_advisory_desc: "7-రోజుల సూక్ష్మవాతావరణ అంచనా",
    rain_alert: "వర్షం హెచ్చరిక",
    disease_desc: "నివారణల కోసం ఆకు గాయాలను స్కాన్ చేయండి",
    instant_ai: "తక్షణ AI",
    irrigation_desc: "వాతావరణం & దశ ఆధారిత షెడ్యూల్",
    water_saving: "నీటి పొదుపు",
    market_prices_desc: "లైవ్ మండి ధరలు",
    tomato_up: "టొమాటో ↑ 8%",
    profit_calculator: "లాభం కాలిక్యులేటర్",
    profit_desc: "ఖర్చులు, దిగుబడి & ROI లెక్కించండి",
    financials: "ఆర్థికపరమైనవి",
    open_tool: "సాధనం తెరవండి",
    community_hub_title: "🌾 ఫార్మోగ్రామ్ సంఘం & నాలెడ్జ్ హబ్",
    community_hub_subtitle: "భారతీయ రైతుల నిజమైన అనుభవాలు & ధృవీకరించబడిన సలహాలు",
    share_experience: "మీ అనుభవాన్ని పంచుకోండి"
  },
  kn: {
    home: "ಮುಖಪುಟ",
    weather: "ಹವಾಮಾನ",
    community: "ಸಮುದಾಯ",
    market: "ಮಾರುಕಟ್ಟೆ",
    expert_qa: "ತಜ್ಞರ ಪ್ರಶ್ನೋತ್ತರ",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    good_morning: "ಶುಭೋದಯ",
    your_farm_dashboard: "ನಿಮ್ಮ ಫಾರ್ಮ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    weather_overview: "ಹವಾಮಾನ ಅವಲೋಕನ",
    current_conditions: "ಪ್ರಸ್ತುತ ಪರಿಸ್ಥಿತಿಗಳು",
    actionable_advisories: "ಸಲಹೆಗಳು",
    seven_day_forecast: "7-ದಿನದ ಮುನ್ಸೂಚನೆ",
    login_to_farmogram: "ಲಾಗಿನ್ ಮಾಡಿ",
    mobile_number: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    password: "ಪಾಸ್ವರ್ಡ್",
    register_your_farm: "ನೋಂದಾಯಿಸಿ",
    farmer_onboarding: "ರೈತರ ನೋಂದಣಿ",
    full_name: "ರೈತರ ಪೂರ್ಣ ಹೆಸರು",
    next: "ಮುಂದೆ",
    back: "ಹಿಂದೆ",
    create_password: "ಪಾಸ್ವರ್ಡ್ ರಚಿಸಿ",
    confirm_password: "ಪಾಸ್ವರ್ಡ್ ಖಚಿತಪಡಿಸಿ",
    select_language: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    state: "ರಾಜ್ಯ",
    district: "ಜಿಲ್ಲೆ",
    land_acres: "ಕೃಷಿ ಭೂಮಿ (ಎಕರೆ)",
    soil_type: "ಮಣ್ಣಿನ ಪ್ರಕಾರ",
    primary_crops: "ಮುಖ್ಯ ಬೆಳೆಗಳು",
    create_profile: "ಪ್ರೊಫೈಲ್ ರಚಿಸಿ",
    select_state: "ರಾಜ್ಯವನ್ನು ಆರಿಸಿ",
    select_district: "ಜಿಲ್ಲೆಯನ್ನು ಆರಿಸಿ",
    select_soil: "ಮಣ್ಣಿನ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ",
    search: "ಹುಡುಕಿ...",
    recommended_for_you: "ನಿಮಗಾಗಿ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ",
    market_prices: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು",
    disease_detection: "ರೋಗ ಪತ್ತೆ",
    irrigation: "ನೀರಾವರಿ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    admin_view: "ನಿರ್ವಾಹಕ ವೀಕ್ಷಣೆ",
    farmer_view: "ರೈತ ವೀಕ್ಷಣೆ",
    profit: "ಲಾಭ",
    schemes: "ಯೋಜನೆಗಳು",
    qa: "ಪ್ರಶ್ನೋತ್ತರ",
    smart_agri_decision: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ನಿರ್ಧಾರ ಮತ್ತು ಸಮುದಾಯ",
    main_navigation: "ಮುಖ್ಯ ಸಂಚರಣೆ",
    management: "ನಿರ್ವಹಣೆ",
    settings_subtitle: "ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    language_region: "ಭಾಷೆ ಮತ್ತು ಪ್ರದೇಶ",
    app_language: "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ",
    select_pref_lang: "ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    push_notifications: "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು",
    receive_alerts: "ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ",
    accessibility: "ಪ್ರವೇಶಿಸುವಿಕೆ",
    high_contrast: "ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್ ಮೋಡ್",
    increase_contrast: "ಓದಲು ಸುಲಭವಾಗುವಂತೆ ಮಾಡಿ",
    about_farmogram: "ಫಾರ್ಮೋಗ್ರಾಮ್ ಬಗ್ಗೆ",
    version_info: "ಆವೃತ್ತಿ 1.0.0 (SIH 2026 ಪ್ರೋಟೋಟೈಪ್)"
,

    location: "ಸ್ಥಳ:",
    temperature: "ತಾಪಮಾನ:",
    primary_soil: "ಪ್ರಾಥಮಿಕ ಮಣ್ಣು:",
    active_crops_in_season: "ಋತುವಿನಲ್ಲಿ ಸಕ್ರಿಯ ಬೆಳೆಗಳು",
    agricultural_advisory: "ಕೃಷಿ ಸಲಹೆ:",
    high_priority: "ಹೆಚ್ಚಿನ ಆದ್ಯತೆ",
    view_weather_advisory: "ಹವಾಮಾನ ಸಲಹೆ ವೀಕ್ಷಿಸಿ",
    decision_support_tools: "ನಿರ್ಧಾರ ಬೆಂಬಲ ಪರಿಕರಗಳು",
    pre_sowing_intelligence: "ಬಿತ್ತನೆ ಮೊದಲು ಕಟಾವಿನವರೆಗೆ ಗುಪ್ತಚರ",
    crop_advisor_desc: "AI ಬಹು-ಅಂಶ ಕೃಷಿ ಸಲಹೆ",
    high_precision: "ಹೆಚ್ಚಿನ ನಿಖರತೆ",
    weather_advisory: "ಹವಾಮಾನ ಸಲಹೆ",
    weather_advisory_desc: "7-ದಿನದ ಸೂಕ್ಷ್ಮ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",
    rain_alert: "ಮಳೆ ಎಚ್ಚರಿಕೆ",
    disease_desc: "ಪರಿಹಾರಕ್ಕಾಗಿ ಎಲೆಗಳ ಗಾಯಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    instant_ai: "ತತ್ಕ್ಷಣದ AI",
    irrigation_desc: "ಹವಾಮಾನ ಮತ್ತು ಹಂತ-ಆಧಾರಿತ ವೇಳಾಪಟ್ಟಿ",
    water_saving: "ನೀರು ಉಳಿತಾಯ",
    market_prices_desc: "ಲೈವ್ ಮಂಡಿ ದರಗಳು",
    tomato_up: "ಟೊಮೆಟೊ ↑ 8%",
    profit_calculator: "ಲಾಭ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    profit_desc: "ವೆಚ್ಚಗಳು, ಇಳುವರಿ ಮತ್ತು ROI",
    financials: "ಹಣಕಾಸು",
    open_tool: "ಪರಿಕರ ತೆರೆಯಿರಿ",
    community_hub_title: "🌾 ಫಾರ್ಮೋಗ್ರಾಮ್ ಸಮುದಾಯ ಮತ್ತು ಜ್ಞಾನ ಕೇಂದ್ರ",
    community_hub_subtitle: "ಭಾರತೀಯ ರೈತರ ನೈಜ ಅನುಭವಗಳು ಮತ್ತು ಪರಿಶೀಲಿಸಿದ ಸಲಹೆಗಳು",
    share_experience: "ನಿಮ್ಮ ಅನುಭವ ಹಂಚಿಕೊಳ್ಳಿ"
  },
  ml: {
    home: "ഹോം",
    weather: "കാലാവസ്ഥ",
    community: "കമ്മ്യൂണിറ്റി",
    market: "മാർക്കറ്റ്",
    expert_qa: "വിദഗ്ദ്ധ ചോദ്യോത്തരം",
    notifications: "അറിയിപ്പുകൾ",
    profile: "പ്രൊഫൈൽ",
    good_morning: "സുപ്രഭാതം",
    your_farm_dashboard: "നിങ്ങളുടെ ഫാം ഡാഷ്ബോർഡ്",
    weather_overview: "കാലാവസ്ഥാ അവലോകനം",
    current_conditions: "നിലവിലെ അവസ്ഥ",
    actionable_advisories: "ഉപദേശങ്ങൾ",
    seven_day_forecast: "7 ദിവസത്തെ പ്രവചനം",
    login_to_farmogram: "ലോഗിൻ ചെയ്യുക",
    mobile_number: "മൊബൈൽ നമ്പർ",
    password: "പാസ്‌വേഡ്",
    register_your_farm: "നിങ്ങളുടെ ഫാം രജിസ്റ്റർ ചെയ്യുക",
    farmer_onboarding: "കർഷക രജിസ്ട്രേഷൻ",
    full_name: "കർഷകന്റെ മുഴുവൻ പേര്",
    next: "അടുത്തത്",
    back: "പിന്നിലേക്ക്",
    create_password: "പാസ്‌വേഡ് സൃഷ്ടിക്കുക",
    confirm_password: "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
    select_language: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    state: "സംസ്ഥാനം",
    district: "ജില്ല",
    land_acres: "കൃഷിഭൂമി (ഏക്കർ)",
    soil_type: "മണ്ണിന്റെ തരം",
    primary_crops: "പ്രധാന വിളകൾ",
    create_profile: "പ്രൊഫൈൽ സൃഷ്ടിക്കുക",
    select_state: "സംസ്ഥാനം തിരഞ്ഞെടുക്കുക",
    select_district: "ജില്ല തിരഞ്ഞെടുക്കുക",
    select_soil: "മണ്ണിന്റെ തരം തിരഞ്ഞെടുക്കുക",
    search: "തിരയുക...",
    recommended_for_you: "നിങ്ങൾക്കായി ശുപാർശ ചെയ്യുന്നത്",
    market_prices: "മാർക്കറ്റ് വിലകൾ",
    disease_detection: "രോഗനിർണ്ണയം",
    irrigation: "ജലസേചനം",
    settings: "ക്രമീകരണങ്ങൾ",
    admin_view: "അഡ്മിൻ കാഴ്ച",
    farmer_view: "കർഷക കാഴ്ച",
    profit: "ലാഭം",
    schemes: "പദ്ധതികൾ",
    qa: "ചോദ്യോത്തരങ്ങൾ",
    smart_agri_decision: "സ്മാർട്ട് അഗ്രി തീരുമാനം & കമ്മ്യൂണിറ്റി",
    main_navigation: "പ്രധാന നാവിഗേഷൻ",
    management: "മാനേജ്മെന്റ്",
    settings_subtitle: "മുൻഗണനകൾ കൈകാര്യം ചെയ്യുക",
    language_region: "ഭാഷയും പ്രദേശവും",
    app_language: "ആപ്പ് ഭാഷ",
    select_pref_lang: "ഇഷ്ടപ്പെട്ട ഭാഷ തിരഞ്ഞെടുക്കുക",
    push_notifications: "അറിയിപ്പുകൾ",
    receive_alerts: "കാലാവസ്ഥാ അലർട്ടുകൾ സ്വീകരിക്കുക",
    accessibility: "ആക്സസിബിലിറ്റി",
    high_contrast: "ഉയർന്ന കോൺട്രാസ്റ്റ് മോഡ്",
    increase_contrast: "വായിക്കാൻ എളുപ്പമാക്കുക",
    about_farmogram: "ഫാർമോഗ്രാമിനെക്കുറിച്ച്",
    version_info: "പതിപ്പ് 1.0.0 (SIH 2026 പ്രോട്ടോടൈപ്പ്)"
,

    location: "സ്ഥലം:",
    temperature: "താപനില:",
    primary_soil: "പ്രധാന മണ്ണ്:",
    active_crops_in_season: "സീസണിലെ പ്രധാന വിളകൾ",
    agricultural_advisory: "കാർഷിക ഉപദേശം:",
    high_priority: "ഉയർന്ന മുൻഗണന",
    view_weather_advisory: "കാലാവസ്ഥാ ഉപദേശം കാണുക",
    decision_support_tools: "തീരുമാന പിന്തുണാ ഉപകരണങ്ങൾ",
    pre_sowing_intelligence: "വിത്ത് പാകുന്നത് മുതൽ വിളവെടുപ്പ് വരെയുള്ള വിവരങ്ങൾ",
    crop_advisor_desc: "AI അടിസ്ഥാനമാക്കിയുള്ള കാർഷിക ഉപദേശം",
    high_precision: "ഉയർന്ന കൃത്യത",
    weather_advisory: "കാലാവസ്ഥാ ഉപദേശം",
    weather_advisory_desc: "7-ദിവസത്തെ കാലാവസ്ഥാ പ്രവചനം",
    rain_alert: "മഴ അലർട്ട്",
    disease_desc: "രോഗപരിഹാരങ്ങൾക്കായി ഇലകൾ സ്കാൻ ചെയ്യുക",
    instant_ai: "തൽക്ഷണ AI",
    irrigation_desc: "കാലാവസ്ഥയും വളർച്ചാ ഘട്ടവും അനുസരിച്ചുള്ള ജലസേചനം",
    water_saving: "ജല സംരക്ഷണം",
    market_prices_desc: "തത്സമയ മാർക്കറ്റ് വിലകൾ",
    tomato_up: "തക്കാളി ↑ 8%",
    profit_calculator: "ലാഭ കാൽക്കുലേറ്റർ",
    profit_desc: "ചെലവുകൾ, വിളവ്, ROI എന്നിവ കണക്കാക്കുക",
    financials: "സാമ്പത്തികം",
    open_tool: "ടൂൾ തുറക്കുക",
    community_hub_title: "🌾 ഫാർമോഗ്രാം കമ്മ്യൂണിറ്റി & നോളഡ്ജ് ഹബ്",
    community_hub_subtitle: "ഇന്ത്യൻ കർഷകരുടെ അനുഭവങ്ങളും പരിശോധിച്ച ഉപദേശങ്ങളും",
    share_experience: "നിങ്ങളുടെ അനുഭവം പങ്കിടുക"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('farmogram_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('farmogram_lang', currentLang);
  }, [currentLang]);

  const t = (key) => {
    if (!translations[currentLang]) return key;
    if (!translations[currentLang][key]) {
      // Fallback to English if translation is missing
      return translations['en'][key] || key;
    }
    return translations[currentLang][key];
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setCurrentLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
